auth0/wordpress

templates/initial-setup/partials/header.php
Otherwise if accessed from an https page, it will complain re: mixed content
=> Force logo to https

lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, templates/auth0-singlelogout-handler.php, templates/auth0-sso-handler-lock10.php
=> fix SSO and SLO with lock 10

WP_Auth0.php, lib/WP_Auth0_LoginManager.php, lib/php-jwt/Authentication/JWT.php
Provide greater hints related to the base64 encoding issue. 
**Current**
**PR**
**Plugin Error Log**
**Current**
**PR**
=> Expand internal login error with hint to disable base 64 encoding

README.md
Correct spelling of "does" in the "How does it work?" link under Customize users matching.
=> Update README.md to correct spelling

CHANGELOG.md, README.md, WP_Auth0.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/initial-setup/WP_Auth0_InitialSetup_ConnectionProfile.php, readme.txt
**Changed**
- Update /authorize URL [\#326](https://github.com/auth0/wp-auth0/pull/326) ([cocojoe](https://github.com/cocojoe))
=> Release 3.2.23

CHANGELOG.md, README.md, WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Configure_JWTAUTH.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, lib/WP_Auth0_Routes.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/initial-setup/WP_Auth0_InitialSetup_AdminUser.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, lib/initial-setup/WP_Auth0_InitialSetup_Migration.php, readme.txt, templates/a0-widget-setup-form.php, templates/auth0-login-form-lock10.php, templates/auth0-singlelogout-handler.php, templates/auth0-sso-handler-lock10.php, templates/initial-setup/connections.php, templates/initial-setup/enterprise_connections.php, templates/initial-setup/signup.php, templates/login-form.php, templates/settings.php
**Added**
- Added Lock 11 / Auth0 9.0, Updated SSO, JWT Algorithm Upgrade Fixes [\#350](https://github.com/auth0/wp-auth0/pull/350) ([cocojoe](https://github.com/cocojoe))
- Add RS256 support [\#331](https://github.com/auth0/wp-auth0/pull/331) ([renrizzolo](https://github.com/renrizzolo))
**Fixed**
- Switching wizard admin user creation to use /dbconnections/signup  [\#356](https://github.com/auth0/wp-auth0/pull/356) ([joshcanhelp](https://github.com/joshcanhelp))
=> Release 3.4.0

templates/initial-setup/admin-creation.php, templates/initial-setup/connection_profile.php
A small hotfix on a text change in the error message.
=> Correcting accessible typo in admin-creation.php and connection_profile.php in initial-setup templates

WP_Auth0.php
When using the [auth0] shortcode with no declared attributes, there was a warning error shown.
=> Fixed shortcode warning

WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_LoginManager.php, lib/initial-setup/WP_Auth0_InitialSetup.php
- Upgrading Lock 11.0.0 => 11.1
- Upgrading Auth.js 9.0.0 => 9.1
- Checking for an existing client grant for the management API before failing
- Admin notice if client grant is successful to info and catch edge cases
Waiting for #366 to be completed before submitting
=> Fixing DB version upgrade

lib/WP_Auth0_Routes.php
=> Changing algorithm for migration tokens

CHANGELOG.md, README.md, WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/admin/WP_Auth0_Admin_Basic.php, readme.txt
**Fixed**
- Fixed Client Grant Types during update [\#377](https://github.com/auth0/wp-auth0/pull/377) ([joshcanhelp](https://github.com/joshcanhelp))
=> Release 3.5.1

WP_Auth0.php
=> Fixed get_avatar hooked function to account for other user identifiers

WP_Auth0.php
=> Deleting all added options and transients on uninstall

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_LoginManager.php
Deprecation notices on 2 public methods that are not used anywhere in the plugin.
=> Deprecate oauth/ro endpoint

lib/WP_Auth0_LoginManager.php
No functional changes. Completed using:
```bash
phpcbf ./lib/WP_Auth0_LoginManager.php --standard=WordPress
```
... then manually adjusting where needed. Guidelines are here:
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/
=> Whitespace, method order, and linebreaks in lib/WP_Auth0_LoginManager.php

composer.json, composer.lock, phpcs-ruleset.xml
Adding CodeSniffer support with a custom ruleset for auto-correcting whitespace, scanning for code/style issues, and checking for PHP version compatibility. This PR has no affect on plugin functionality.
=> Add code quality tools, improved composer.json

WP_Auth0.php, assets/css/login.css, lib/WP_Auth0_Amplificator.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/initial-setup/WP_Auth0_InitialSetup_Connections.php, templates/a0-widget-setup-form.php
- Remove beta plugin (#400) 
- Fix shorthand array
- `die` -> `exit` for consistency
- `parse_url()` -> `wp_parse_url()` as recommended by WordPress
=> Fix pre release issues

assets/js/admin.js, lib/admin/WP_Auth0_Admin.php, templates/import_settings.php, templates/settings.php
=> Fix import-export tabs not working

lib/WP_Auth0_Lock10_Options.php
=> Show signup tab if action=register on wp-login.php page

assets/js/lock-init.js, templates/auth0-login-form.php
=> Fix missing signup fields

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Import_Settings.php, lib/WP_Auth0_UsersRepo.php, templates/import_settings.php
- Fix install URLs
- Remove constant settings from export
- Fix PHP notice if no email on login
=> Fixes found during testing 3.7.0

CONTRIBUTION.md, README.md, WP_Auth0.php
Changes needed to merge the `dev` branch into `master`
=> Update README and version number for dev->master merge

lib/WP_Auth0_Api_Client.php
Deprecation docblocks and error triggering for unused methods in the `WP_Auth0_Api_Client` class. Also moved all deprecated methods to the bottom of the class.
=> Deprecate unused methods in WP_Auth0_Api_Client

lib/WP_Auth0_EditProfile.php
Deprecation docblocks and error triggering for unused methods in the `WP_Auth0_EditProfile` class. Also moved all deprecated methods to the bottom of the class. 
=> Deprecations for WP_Auth0_EditProfile

CHANGELOG.md, WP_Auth0.php, lib/WP_Auth0_RulesLib.php
- Merge in 3.7.1 path release
- [3.7.1 release](https://github.com/auth0/wp-auth0/releases/tag/3.7.1)
- [Already reviewed in #463 PR](https://github.com/auth0/wp-auth0/pull/563)
=> Merge 3.7.1

WP_Auth0.php, tests/testRenderForm.php
Moved the logged-in user check and redirect to an earlier hook.
=> Move logged-in user redirection to an earlier hook

CHANGELOG.md, WP_Auth0.php, readme.txt
[Release milestone](https://github.com/auth0/wp-auth0/milestone/22)
- CHANGELOG update
- WP.org readme update
- New version number
=> Release 3.8.1

CHANGELOG.md, WP_Auth0.php, readme.txt
Changelog, readme, and plugin version updates.
=> Release 3.9.0

WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_EditProfile.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php, lib/api/WP_Auth0_Api_Abstract.php, lib/initial-setup/WP_Auth0_InitialSetup_Connections.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, lib/initial-setup/WP_Auth0_InitialSetup_Migration.php, lib/initial-setup/WP_Auth0_InitialSetup_Rules.php
=> Notes for Management API inventory

lib/WP_Auth0_LoginManager.php, tests/testLoginManager.php
Remove telemetry from generated Auth0 URLs.
=> Remove telemetry from authorize and logout URLs

lib/WP_Auth0_WooCommerceOverrides.php
Ran `composer phpcbf` to fix whitespace from #630
=> Fix whitespace from previous PR

lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, tests/testWPAuth0Options.php
Removing stored values and setting keys for previously-removed settings.
=> Remove previously-deleted settings

lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Basic.php
- Reorder Embedded options
- Minor re-wording on 2 other options
=> Settings page adjustments

WP_Auth0.php, tests/testWPAuth0DbMigrations.php
Update default Lock version from 11.14 -> 11.15
[Lock changelog](https://github.com/auth0/lock/blob/master/CHANGELOG.md)
=> Update default Lock to 11.5

composer.json, lib/WP_Auth0_Id_Token_Validator.php, lib/WP_Auth0_LoginManager.php, lib/exceptions/WP_Auth0_InvalidIdTokenException.php, tests/testIdTokenValidator.php
Adds issuer and audience ID token validation everywhere ID tokens are used.
=> Add issuer and audience ID token validation

assets/css/login.css
Just group `#auth0-login-form` selectors into one.
=> Edit login.css

CHANGELOG.md, WP_Auth0.php, readme.txt
See changelog below or the [milestone](https://github.com/auth0/wp-auth0/milestone/24?closed=1) for all changes in this release.
=> Release 3.11.0

CHANGELOG.md, WP_Auth0.php, readme.txt
See the changelog below or [milestone](https://github.com/auth0/wp-auth0/milestone/25?closed=1) for information on this release.
=> Release 3.11.1

lib/WP_Auth0_UsersRepo.php
- Remove `$access_token`, `$role`, and `$skip_email_verified` from `WP_Auth0_UsersRepo::create()`
- Add docblocks
=> Remove deprecated from WP_Auth0_UsersRepo

lib/token-verifier/WP_Auth0_IdTokenVerifier.php
Remove `iat` claim value check for ID token validation; continue to check for presence.
=> Remove future iat check

CHANGELOG.md, WP_Auth0.php, readme.txt
See changelog below or [milestone](https://github.com/auth0/wp-auth0/issues?q=is%3Aclosed+milestone%3A3.11.2) for information on this release.
=> Release 3.11.2

lib/WP_Auth0_Api_Client.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testInitialSetupConsent.php
Remove the automatic connection disabling that happens on setup. This should be managed in the tenant settings.
=> Remove connection deactivation on setup

WP_Auth0.php
=> Fix potential XSS on wp-login.php override page

CHANGELOG.md, WP_Auth0.php, readme.txt, tests/testAdminAppearanceValidation.php, tests/testEmbedWidget.php
See milestone or CHANGELOG below for changes.
=> Release 3.11.3

CHANGELOG.md, WP_Auth0.php, lib/WP_Auth0_Options.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testWPAuth0DbMigrations.php, tests/testWPAuth0Options.php
Merge in changes from [previous 2 patch versions](https://github.com/auth0/wp-auth0/compare/3.11.1...3.11.3).
=> Merge in 3.11.2 and 3.11.3

tests/testShortcode.php, tests/traits/wpScriptsHelper.php
Tests for shortcode output, no functionality changes.
#789
=> Add tests for shortcode output

WP_Auth0.php
Fix an incorrect function loaded in the uninstall hook
=> Fix incorrect function in uninstall hook

CHANGELOG.md, WP_Auth0.php, readme.txt
See the changelog below or the [milestone](https://github.com/auth0/wp-auth0/milestone/28) for information on this release.
=> Release 4.1.0

CHANGELOG.md, WP_Auth0.php, readme.txt
See Milestone for changes in this version:
https://github.com/auth0/wp-auth0/issues?q=is%3Aclosed+milestone%3A4.1.1
=> Release 4.1.1

CHANGELOG.md, WP_Auth0.php, readme.txt
See the `CHANGELOG` in this PR or [milestone](https://github.com/auth0/auth0-PHP/milestone/25) for details about this release.
=> Release 4.2.0

readme.txt
Updates the README to reflect plugin support for WordPress 5.7 in the plugins catalog.
=> [SDK-2379] Reflect WP 5.7 support

CHANGELOG.md, WP_Auth0.php
**Added**
- Add support for Auth0 Organizations [\#827](https://github.com/auth0/wp-auth0/pull/827) ([evansims](https://github.com/evansims))
=> Release 4.3.0

WP_Auth0.php, assets/css/login.css, lib/WP_Auth0_Lock.php, tests/testLockOptions.php
This PR;
- Resolves an issue with embedded logins where the client configuration URL built by the plugin points to an out of date path.
- Updates the versions of Lock and Auth0.js imported by the plugin.
- Fixes some CSS issues stemming from the JS library upgrades.
=> [SDK-2788] Update client configuration url for embedded logins

README.md
This PR updates the README with additional installation and configuration instructions for V5 GA.
=> v5.0 README updates
