auth0/wordpress

WP_Auth0.php
when a user logs in for the first time and the username collision with an existing WP user, it can gain access to the user with id# 1.
=> Security vulnerability fix on login

README.md, WP_Auth0.php, assets/css/login.css, lib/WP_Auth0_Api_Client.php, templates/back-to-auth0.php, templates/login-form.php
Auto Login (no widget) Does not work with WooCommerce My Account Login #45
=> Added support for WooCommerce + updated info headers

README.md, WP_Auth0.php, lib/WP_Auth0_Admin.php, lib/WP_Auth0_Options.php, templates/a0-widget-setup-form.php, templates/auth0-login-form.php
Hardwired redirect url after login #71
Add custom js to add custom buttons #73
=> fix implicit wf in subdirectories, added custom JS

WP_Auth0.php, lib/WP_Auth0_Admin.php, lib/WP_Auth0_Options.php, templates/auth0-login-form.php
=> Added SSO features

WP_Auth0.php
The un-scoped call to unserialize has been observed to call functions from other plugins. Adding Scope Resolution ensures the correct function is called.
=> Added Scope Resolution to unserialize function call

lib/WP_Auth0_LoginManager.php, lib/exceptions/WP_Auth0_BeforeLoginException.php
Allows 3rd party plugins to run, check other conditions and throw an exception if login is to be prevented. Includes special logout display and link for these cases.  I am trying to integrate the Auth0 login plugin with the WP-Members 'hold registrations for admin approval' feature, and this hook gets me most of the way there.
I included a small refactor of the actual logic for doing the wordpress login into a do_login() function.
I just picked "before_login" as the first name that came to mind -- feel free to suggest a better one.
=> Add auth0_before_login hook and exception type

WP_Auth0.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, templates/auth0-singlelogout-handler.php, templates/auth0-sso-handler-lock10.php
=> Release 3.2.18

lib/WP_Auth0_LoginManager.php, lib/php-jwt/Authentication/JWT.php
JWTDecode exceptions are now caught and logged in Auth0 Error Log, which should aid CS in debugging in general.  A leeway (could be increased) for clock skew has been added to iat, nbf and exp claims. 
Related to a current ZD Ticket
=> Improve redirect_login error logging, JWT leeway

lib/WP_Auth0_Options.php
Since all new clients created are not base64 encoded, it does not make
sense to keep this turned on by default.
=> Disable base64_encoded by default

CHANGELOG.md, README.md, WP_Auth0.php, lib/WP_Auth0_LoginManager.php
**Added**
- Improve redirect_login error logging, JWT leeway [\#317](https://github.com/auth0/wp-auth0/pull/317) ([cocojoe](https://github.com/cocojoe))
**Changed**
- Expand internal login error with hint to disable base 64 encoding [\#318](https://github.com/auth0/wp-auth0/pull/318) ([cocojoe](https://github.com/cocojoe))
- Disable base64_encoded by default [\#313](https://github.com/auth0/wp-auth0/pull/313) ([thameera](https://github.com/thameera))
=> Release 3.2.21

WP_Auth0.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/php-jwt/Authentication/JWT.php
Fixed base64 flag not being stored as boolean
=> Fixed migration for older plugins that use base64 secret

CHANGELOG.md, WP_Auth0.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/php-jwt/Authentication/JWT.php
**Fixed**
- Fixed migration for older plugins that use base64 secret [\#324](https://github.com/auth0/wp-auth0/pull/324) ([cocojoe](https://github.com/cocojoe))
=> Release 3.2.22

lib/admin/WP_Auth0_Admin_Advanced.php, readme.txt
As seen on https://wordpress.org/plugins/auth0/faq/
=> Fix typos seen when installing plugin and in advanced admin

CHANGELOG.md, WP_Auth0.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/php-jwt/Authentication/JWT.php
**Changed**
- More generous JWT leeway [\#332](https://github.com/auth0/wp-auth0/pull/332) ([cocojoe](https://github.com/cocojoe))
**Removed**
- Remove client_id/secret validation since it is not allowed anymore [\#334](https://github.com/auth0/wp-auth0/pull/334) ([glena](https://github.com/glena))
=> Release 3.2.24

lib/WP_Auth0_Metrics.php
The `metricsTrack` function, used throughout the admin panel, is undefined if the setting to allow anonymous analytics is disabled. This change defines a no-op function of the same name when analytics are disabled to avoid the script errors.
More than just a few errors in the console, this problem was causing the switches on the Connections page to not work. Analytics click handlers on the switches were tossing an exception which blocked the code that handled the switch functionality.
=> Prevent script errors throughout the admin panel when anonymous data metrics are disabled

lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_UsersRepo.php
A few of the user-facing exception messages regarding existing accounts and inability to sign up were not translatable. This does not affect developer-facing exceptions.
This issue was first encountered in #308 to which a fix has not yet been determined. I was unable to change the default "Could not create user. The registration process is not available. Please contact your site’s administrator." message to say something more specific like "Billing login is available only for subscription managers."
See #311 for the rationale of using 'wp-auth0' rather than `WPA0_LANG` in this commit.
=> Added translation support for a few user-facing exception messages

lib/WP_Auth0_Api_Client.php, lib/initial-setup/WP_Auth0_InitialSetup_AdminUser.php
In testing dev, @cocojoe and I found that the /api/v2/users endpoint used in `WP_Auth0_Api_Client::create_user` would not authenticate because the API Client being used was not being activated by default for the Database Connection that was being made. We created a new method, `WP_Auth0_Api_Client::signup_user` to use the Authentication signup endpoint.
=> Switching wizard admin user creation to use /dbconnections/signup 

lib/WP_Auth0_Routes.php
JWT::decode() expects a third parameter for allowed algorithms that was not being passed in the migration process.
=> Fixing "Algorithm not allowed" error during user migration

WP_Auth0.php
When activating using [wp-cli](http://wp-cli.org/) the plugin should not redirect.
See https://github.com/wp-cli/wp-cli/blob/16bb1aac5bc188b42c0037a255f60efdf1f0db93/php/wp-cli.php#L4
This change fixes the following warning on plugin activation:
````
Warning: Some code is trying to do a URL redirect. Backtrace:
#0  WP_CLI\Utils\wp_redirect_handler(http:/wp-admin/admin.php?page=wpa0) called at [/var/www/html/wp-includes/class-wp-hook.php:300]
#1  WP_Hook->apply_filters(http:/wp-admin/admin.php?page=wpa0, Array ([0] => http:/wp-admin/admin.php?page=wpa0,[1] => 302)) called at [/var/www/html/wp-includes/plugin.php:203]
#2  apply_filters(wp_redirect, http:/wp-admin/admin.php?page=wpa0, 302) called at [/var/www/html/wp-includes/pluggable.php:1190]
#3 …
```
=> When activating using wp-cli the plugin should not redirect

WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/initial-setup/WP_Auth0_InitialSetup.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php
Clients used with this plugin need to have a specific grant to the management API in order to handle certain actions like verification emails. The client also needs to have an app_type set, in this case "Regular Web Application."
This pull request:
- Adds the app_type and client_grant to the client creation process when the plugin is first installed
- Updates the DB version to 16 and attempts to fix the app_type and client_grant
- If this process fails, a flag is set as an option and a banner with instructions will appear until the process is complete
- Added a process to extra the audience from a manually-added app token during validation
- Added a check for the client grant when an app token is saved to re-run the client_grant process
- A few spelling and formatting errors throughout
=> Creating client_grant for management API

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Email_Verification.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_LoginManager.php
This PR changes where user information comes from on login. Switching from the Auth API /userinfo to the Management API /users/user_id to get identities. 
* Added WP_Auth0_Api_Client::get_client_token() to quickly get a management token
* Updated WP_Auth0_Api_Client::resend_verification_email() to use this token function
* Replaced WP_Auth0_Api_Client::get_user_info() with WP_Auth0_Api_Client::get_user() to return user information during login (management API access is acquired as part of this upgrade), which fixes identities being returned
* Added read:users as a required scope
* Updated DB upgrade to use new WP_Auth0_Api_Client::get_client_token() function to confirm that a client_credentials token can be returned
=> Added use Management API for user data

lib/WP_Auth0_Routes.php
Changing allowed algorithm for migration token to always be HS256
=> Migration tokens only use HS256

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, templates/initial-setup/connection_profile.php
Main goal here is moving from storing the API audience from the API token to creating a settings field to hold one with the system Management API audience (most likely to be used in the vast majority of installs) as a default. 
Also:
* Fixed up `WP_Auth0_Api_Client::get_client_token()` do use recommended Content-Type header
* Updated 2 docs links, relevant to the updates in this release
* Removed empty cache_expiration setting check (can be 0 for no caching)
* Added client update procedure from DB v15 to DB v16 to catch `site_url()` update
=> Fixed automatic setup process for public sites

CHANGELOG.md, README.md, WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/admin/WP_Auth0_Admin_Basic.php
Older legacy clients may not have the `client_credentials` Grant Type activated in their Client Advanced settings. This will prevent them from getting a Management API token, breaking functionality in a number of places. This can be remedied manually in **[Client Advanced Settings](https://auth0.com/docs/cms/wordpress/configuration#client-setup) > Grant Types** tab, activating the **Client Credentials** type. 
This PR adds a DB version and attempts to update this automatically if there is a valid API token saved in wp-admin. It also enforces the correct `grant_types` during client creation and adds a note to the README and CHANGELOG regarding the 3.5.0 update.
=> Fixed Client Grant Types during update

lib/WP_Auth0_LoginManager.php
Reported in #381, we're allowing unsanitized HTML to pass from a URL query param into a message to users unable to log in.
=> XSS in error query vars

lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php
Swapped in `array_replace_recursive` instead of `array_merge_recursive` to avoid an array being created that the Lock widget couldn't understand.
=> Fixed wrong title and icon for login widget

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_ErrorManager.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Routes.php, lib/WP_Auth0_UsersRepo.php, lib/admin/WP_Auth0_Admin_Basic.php
- Using `__METHOD__` magic constant instead of hard-coded method name
- Improved WP_Auth0_ErrorManager:: insert_auth0_error() based on #285
=> Changed error handling

WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_Options.php, lib/WP_Auth0_Routes.php
* Refactored `WP_Auth0_Api_Client::create_client()` to improve the URLs being saved by default and combine create with update (`web_origins` can now be pushed during create)
* Fix for blank site title causing client create to fail [reported here](https://wordpress.org/support/topic/auth0-setup-wizard-fails/)
* Helper functions on `WP_Auth0_DBManager` to grab correct links in the correct format
=> Improved setup wizard client create process

lib/WP_Auth0_Api_Client.php
Missed a reference to the function deprecated then reverted in #391
=> Renaming un-deprecated function

WP_Auth0.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_State_Handler.php, templates/auth0-singlelogout-handler.php
The WordPress plugin doesn't not currently handle state checking at all. A value is set in Lock and sent back but not stored and checked. This PR:
- Adds a `WP_Auth0_State_Handler` class used to generate, store, and validate a state nonce using cookies
- Adjusts Lock to use the new nonce value and stores it as a cookie
- Checks for this value during login for both flows, redirect and implicit
- Adds a `WP_Auth0_LoginManager->die_on_login()` method to handling error message display for login errors
- Adjusts the `auth0-singlelogout-handler.php` to not pull Lock options and skip anything related to state
=> State handling during login process for both types

WP_Auth0.php, lib/WP_Auth0_LoginManager.php
WP_Auth0_LoginManager was not processing errors well, was poorly
documented, and might have been improperly exposing error messages.
Incoming URL param errors from Auth0 and configuration issues are caught
earlier in the login process. Error message are not exposed to the
user; instead they are logged for an admin. Thrown errors are
standarized and listed in docblocks.
Fixes #305
=> Fix Login Process Error Handling

lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_State_Handler.php
The implicit login flow redirects to the login page to handle the
response from Auth0. This caused the cookie to be set to a new value
before the state being returned is checked. The state was also not
urldecoded so "=" chars were being received as "%3D" and were not being
base64 decoded properly.
=> Fix state handling for Implicit flow

WP_Auth0.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Nonce_Handler.php, lib/WP_Auth0_State_Handler.php, templates/auth0-login-form-lock10.php
State generation, specifically cookie storage, needs to happen before
any output. The previous arch was ok for login page generation but
failed with a "headers already set" error if used in the shortcode.
This addresses the issue by storing state earlier and getting the
value later.
=> Fix improper state handling

lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_Options.php, lib/WP_Auth0_Options_Generic.php, lib/admin/WP_Auth0_Admin_Advanced.php
Adding get_lock_connections and add_lock_connection for working with
separated options field. reordering option defaults, remove comments,
add docblocks
=> Improve WP_Auth0_Options

WP_Auth0.php, lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Dashboard.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Age.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Gender.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Generic.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_IdP.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Income.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Location.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Signups.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Widgets.php, templates/settings.php
The dashboard widgets clutter the admin, do not display usable data,
and create an unecessary maintenance burden. This functionality can
easily be re-created as a separate plugin if necessary.
This commit will remove the dashboard widgets output, remove related
settings, and add TODOs for proper deprecation.
=> Remove dashboard widgets

lib/WP_Auth0_Import_Settings.php, lib/admin/WP_Auth0_Admin.php, lib/initial-setup/WP_Auth0_InitialSetup.php
This commit will remove duplicate error messages when the plugin is not
setup, use proper HTML format for error messages, and sanitize URL
parameters that are output in messages.
=> Clean up admin notices

WP_Auth0.php, lib/WP_Auth0_Configure_JWTAUTH.php, lib/WP_Auth0_Embed_Widget.php, lib/WP_Auth0_ErrorLog.php, lib/WP_Auth0_Export_Users.php, lib/WP_Auth0_Import_Settings.php, lib/WP_Auth0_Settings_Section.php, lib/WP_Auth0_SocialAmplification_Widget.php, lib/admin/WP_Auth0_Admin.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Location.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Widgets.php, lib/initial-setup/WP_Auth0_InitialSetup.php, lib/initial-setup/WP_Auth0_InitialSetup_Connections.php, templates/login-form.php
- Move asset URLs to constants
- Combine multiple instances of scripts and styles being enqueued in the admin to one place
- Combine multiple instances of Lock URLs to one place
=> Change asset enqueuing

lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php
Setting names were incorrect, confusing in some cases, and used
inconsistent capitalization.
Rewrite setting names and adding proper translations. Add opt names to
the settings array for more simple HTML output (upcoming PR). Add a
filter to add or modify settings array. Changed Client => Application.
=> Setting titles and option names

WP_Auth0.php, assets/js/implicit-login.js, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Nonce_Handler.php, lib/admin/WP_Auth0_Admin_Advanced.php, templates/auth0-login-form-lock10.php
- Fixed error handling for implicit login
- Moved implicit handling JS to own file; refactored
- Added nonce handling for auto-login
- Added state handling for auto-login
- Better nonce generator if < PHP 7 (`openssl_random_pseudo_bytes()`)
=> Fix Implicit login handling

WP_Auth0.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_Options.php, lib/WP_Auth0_Options_Generic.php, lib/admin/WP_Auth0_Admin_Advanced.php, templates/settings.php
Removes the passwordless method and CDN URL settings. Method is removed to simplify the wp-admin and move passwordless management to the Dashbaord. Passwordless URL is hard-coded to new combined Lock, removing the settings field to change that as well. Going forward, Lock will use the same library for both login form types. Also added a DB version bump and migration script to modify the connections setting so the login form will work as expected after a plugin update. Added a handful of TODOs that will be better suited for a future branch (same release).
=> Remove and migrate Passwordless setting

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_ErrorManager.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_LoginManager.php
Some customers are having trouble with the upgrade process in 3.5.2 while others made make changes to their account disabling management API access. This fallback allows user data to be pulled for logging-in users. Also adds requested scopes for auth code login to make this possible and updates the error manager class to handle a common error case.
=> Add /userinfo fallback during login

README.md, readme.txt
Changes made below have already been made in the `dev` branch. Anything that mentioned "Client" was slated to move to the docs site.
=> Changing Client to Application in readme files

lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Generic.php
This commit will:
- Switch Advanced admin settings to use new render functions
- Reword confusing and incorrect descriptions
- Rename incorrect protected vars
- Add check for function_exists to use hooks for settings callbacks
- Fix settings order and option names
=> Change how Advanced admin settings fields are output

lib/WP_Auth0_LoginManager.php
Very minimal functional changes, mostly comments. 
- Added docblocks, parameter + error descriptions, and better inline comments
- Renamed internal variables to conform to snake_case and better describe what they're for
- Changed `urlencode` -> `rawurlencode` per `phpcs` suggestion (RFC-compliant encoding, improves interoperability)
- Changed `die()` -> `exit` for standardization (identical functionality)
- Changed `json_encode()` to `wp_ json_encode()` to catch more problematic encoding
=> Improved code quality in WP_Auth0_LoginManager

lib/WP_Auth0_Lock10_Options.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Features.php
- Refactor Appearance settings with new render functions, new descriptions
- Fix `avatar` Lock setting
- Minor refactor of `WP_Auth0_Admin_Features::render_password_policy()` for consistency
=> Change Appearance tab settings output

lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Dashboard.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php
No functionality changes!
Corrected whitespace with:
```bash
phpcbf ./lib/admin --standard=WordPress
```
Then manually reordered methods to match display order and a handful of empty lines added/removed.
=> Whitespace and method order for wp-admin files

lib/WP_Auth0_Configure_JWTAUTH.php, lib/WP_Auth0_ErrorLog.php, lib/WP_Auth0_Export_Users.php, lib/initial-setup/WP_Auth0_InitialSetup.php
- WP_Auth0_InitialSetup::admin_enqueue()
- WP_Auth0_Configure_JWTAUTH::admin_enqueue()
- WP_Auth0_ErrorLog::init()
- WP_Auth0_ErrorLog::admin_enqueue()
- WP_Auth0_Export_Users::admin_enqueue()
=> Deprecating admin_enqueue functions

lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php
- WP_Auth0_Lock_Options class
- WP_Auth0_Lock10_Options::get_lock_classname()
- WP_Auth0_Lock10_Options::isPasswordlessEnable()
- WP_Auth0_Lock10_Options::get_lock_show_method()
- WP_Auth0_Lock10_Options::get_custom_css()
- WP_Auth0_Lock10_Options::get_custom_js()
- WP_Auth0_Lock10_Options::can_show()
- WP_Auth0_Lock10_Options::get_cdn_url()
- WP_Auth0_Lock10_Options::get_wordpress_login_enabled()
- WP_Auth0_Lock10_Options::set_signup_mode()
- WP_Auth0_Lock10_Options::modal_button_name()
- WP_Auth0_Lock10_Options::get_custom_signup_fields()
- WP_Auth0_Lock10_Options::has_custom_signup_fields()
=> Deprecating unused Lock Options classes and methods

lib/WP_Auth0_Api_Client.php
Changing API header calls to include telemetry always. Also adding server and mysql information.
=> Require telemetry for API calls

WP_Auth0.php, lib/WP_Auth0_Options.php
- WP_Auth0_Options::get_enabled_connections()
- WP_Auth0::get_plugin_dir_url()
=> Deprecate 2 lookup methods

lib/WP_Auth0_LoginManager.php, lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Dashboard.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Age.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Gender.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Generic.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_IdP.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Income.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Location.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Signups.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Widgets.php, lib/initial-setup/WP_Auth0_InitialSetup.php
- WP_Auth0_Admin::cant_connect_to_auth0()
- WP_Auth0_Admin_Advanced::ADVANCED_DESCRIPTION
- WP_Auth0_Admin_Advanced::render_passwordless_enabled()
- WP_Auth0_Admin_Advanced::render_passwordless_method()
- WP_Auth0_Admin_Advanced::connections_validation()
- WP_Auth0_Admin_Appearance::APPEARANCE_DESCRIPTION
- WP_Auth0_Admin_Appearance::render_appearance_description()
- WP_Auth0_Admin_Basic::BASIC_DESCRIPTION
- WP_Auth0_Admin_Basic::render_allow_signup_regular_multisite()
- WP_Auth0_Admin_Basic::render_allow_signup_regular()
- WP_Auth0_Admin_Basic::render_basic_description()
- WP_Auth0_Admin_Dashboard class
- WP_Auth0_Admin_Features::FEATURES_DESCRIPTION
- WP_Auth0_Admin_Features::render_features_description()
- WP_Auth0_Admin_Generic::render_a0_switch()
- WP_Auth0_Dashboard_Plugins_Age …
=> Deprecating wp-admin settings-related methods + classes

lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Nonce_Handler.php, lib/WP_Auth0_Options.php
- Change auto-login logic to be more clear and explicit
- Change implicit to handle nonce correctly
- Add authorize URL param builder
- Fix callback error handling for implicit and redirect
=> Change auto-login action

lib/WP_Auth0_LoginManager.php, templates/auth0-sso-handler-lock10.php
- Remove federated logout for SSO (heavy-handed and was causing [issues](https://community.auth0.com/t/linkedin-logout-not-working-in-wordpress/10997/10) with some users) 
- Remove `end_session` method call (we're not setting any sessions so we should not be deleting any either)
- Fix telemetry header issues (fixes #448)
- Fix SLO link empty issue (`get_permalink()` is empty on non-`post` pages)
- Fix improper filter handling in `auth0_sso_footer` (cannot `echo` in filters, must return modified data)
- Add `no_sso` check for SSO footer on wp-login.php to skip SSO processing if there was a login error (can cause redirect loops)
- Minor code quality fixes (calling out internal methods
=> Fix logout process

lib/WP_Auth0_Lock10_Options.php, templates/auth0-login-form.php, templates/login-form.php
Additional signup fields were overlooked when refactoring Lock output. This PR will add them back.
=> Adding back additional signup fields

lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php
- Fix an error with the returned data type being the wrong error (fixes #464)
- Fix DB update running on new installs
- Fix DB table missing error in install
- Remove references to `use_lock_10` setting in DB update process and defaults
- Change update process to use same Lock version as installation
=> Fix install and DB update errors

lib/WP_Auth0_Lock10_Options.php, lib/admin/WP_Auth0_Admin_Features.php, templates/auth0-singlelogout-handler.php, templates/auth0-sso-handler-lock10.php
The SLO functionality (loads a `checkSession` call on front-end pages if the user is logged in) was using an incorrect `redirectUri` value and also redirected to a malformed logout link (prompted the user to logout instead of doing it automatically). Also:
- Hide and turn off SLO if SSO is not on (fixes #336)
- Removed unnecessary `code` check in SSO `checkSession` call
- More clear `responseType` handling
- Use client credential grant to update Application instead of likely-expired app token
=> Fix SLO redirect, SLO on when SSO off, SSO setting not pushed to dashboard

WP_Auth0.php
=> Fixed auto-loader to skip non-WP-Auth0 classes

lib/WP_Auth0_LoginManager.php, templates/auth0-singlelogout-handler.php
Reported here - https://wordpress.org/support/topic/sso-logout-issues/
SLO is using `home_url()`, which some sites don't have in the "Allowed Callback URLs" field for the Application. Changed to the main Auth0 callback URL which is always there. Callback is not used as a redirect so does not need to change for Implicit, just needs to be valid. 
Also adds SLO check to the admin + login pages and changes the redirect URL used after logout to point to an external page if there is one or the wp-login.php page.
=> Fix SLO callback URL 

lib/WP_Auth0_LoginManager.php
Removed generic `Exception` handling in 3.6.0 as it was catching errors from other plugins. This left the `JWT:decode()` method with no error handling.
=> Add error handling for JWT decode

readme.txt
Update all sections in the WP.org readme file displayed here:
https://wordpress.org/plugins/auth0/
More information about this file here:
https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/
=> Update wordpress.org readme

WP_Auth0.php, lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_RulesLib.php
The WordPress plugin is both disabling signups on the Connection (via API) and social signups (via Rules) based on the WordPress registration setting. This is not good for anyone with multiple Applications using the same connections. Need to remove this functionality and deprecate the functions involved.
- Remove `$this->check_signup_status();` call on initialize
- TODOs for deprecation
=> Remove signup disabling

lib/WP_Auth0_Api_Client.php
Changing to URLs without a query string.
=> Update new Application creation URLs

lib/admin/WP_Auth0_Admin_Advanced.php, tests/testAdvancedOptionsValidation.php
Allows different schemes and subdomains to be used as the login redirection URL. 
Closes #459.
=> Add support for subdomains and different scheme URLs for redirect

lib/WP_Auth0_SocialAmplification_Widget.php
The `identities` property for the user profile can be empty but that was not checked in the widget output.
=> Fix PHP notice for Amplificator widget

lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php
- Fix migration token constant notice
- Replace domain for `get_client_secret_as_key` with auth_domain (uses custom)
=> Fix migration token notice; replace domain with auth_domain

lib/WP_Auth0_LoginManager.php
This fix is to stop processing the login if a user is already logged into WordPress. If the user reaches this point, there is no error from Auth0 and they are already logged into WordPress so there is no need to continue processing the login.
=> Fix login processing if already logged in

lib/WP_Auth0_Options_Generic.php, tests/testConstantSettings.php
Removing the `wp_` prefix for the added hook. This has not been released yet so OK to change the name.
=> Standardize hook name

CHANGELOG.md, WP_Auth0.php, readme.txt
Release PR for 3.7.0. For all changes, see the CHANGELOG below or the [3.7.0 milestone](https://github.com/auth0/wp-auth0/milestone/18?closed=1).
=> Release 3.7.0

WP_Auth0.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Export_Users.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, lib/WP_Auth0_UsersRepo.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Basic.php, tests/bootstrap.php, tests/testCustomDomains.php, tests/testRequiredEmail.php, tests/testUserMeta.php, tests/testUserRepoCreate.php, tests/testWPAuth0Options.php, tests/traits/users.php
**Summary:** Add a setting to the admin that skips email verification for specific strategies. This is being added based on Enterprise strategies that do not provide an `email_verified` flag in the userinfo object. 
**Admin Setting:**
**Specific Changes:**
- Add the `WP_Auth0_UsersRepo::get_meta()` method to abstract getting Auth0 user meta information; refactored all current uses of the core `get_user_meta()` function to use this new method.
- Refactor `WP_Auth0_LoginManager::login_user()` to use the new skip strategies field. 
- Add `WP_Auth0_Options::strategy_skips_verified_email()` method to check whether a specific strategy can be skipped. 
- Refactor `WP_Auth0_UsersRepo::create()` to use the new skip strategies field and simplify logic. 
- Add tests for all new functionality and …
=> Add skip strategies setting and tests

lib/WP_Auth0_LoginManager.php, tests/testLoginManager.php
- Add `WP_Auth0_LoginManager::build_authorize_url()` method to create an authorize link 
- Add `auth0_authorize_url` filter to modify authorize link
- Add `auth0_logout_url` filter to modify Auth0 logout link
- Add tests 🎉 
Closes #521
=> Add filters for authorize URL and params, logout URL + tests

WP_Auth0.php, assets/js/die-with-verify-email.js, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Email_Verification.php, lib/api/WP_Auth0_Api_Abstract.php, lib/api/WP_Auth0_Api_Client_Credentials.php, lib/api/WP_Auth0_Api_Jobs_Verification.php, tests/bootstrap.php, tests/classes/Test_WP_Auth0_Api_Abstract.php, tests/testApiAbstract.php, tests/testApiClientCredentials.php, tests/testEmailVerification.php, tests/testUserMeta.php, tests/testUserRepoCreate.php, tests/traits/ajaxHelpers.php, tests/traits/hookHelpers.php, tests/traits/httpHelpers.php, tests/traits/usersHelper.php
Create a more clear, complete, and easy-to-use access to the Management API, including better error logging when things go wrong. 
- Add `WP_Auth0_Api_Abstract` abstract class to provide a wrapper around the WP HTTP class. This can be extended to add Management API endpoints more easily with built-in error handling. 
- Add `WP_Auth0_Api_Client_Credentials` to perform a Client Credentials grant for API calls
- Add `WP_Auth0_Api_Jobs_Verification` to perform re-send email functionality (mainly to show how the framework is used). 
- Refactor `WP_Auth0_Email_Verification` to use the new API framework, provide better error responses.
- Add multiple test classes and helper traits to test this framework and the resend email functionality, including the ability to halt or mock API calls for …
=> Add Management API framework [WIP]

lib/initial-setup/WP_Auth0_InitialSetup_Connections.php, lib/initial-setup/WP_Auth0_InitialSetup_Migration.php, lib/initial-setup/WP_Auth0_InitialSetup_Rules.php
Deprecation docblocks and error triggering for unused methods and classes related to initial setup. Also moved all deprecated methods to the bottom of the class.
=> Deprecate unused methods and classes for initial setup

lib/WP_Auth0_Referer_Check.php
Deprecation docblocks and error triggering for the unused `WP_Auth0_Referer_Check` class.
=> Deprecate WP_Auth0_Referer_Check

lib/WP_Auth0_Options.php
Deprecation docblocks and error triggering for the unused `set_connection` and `get_connection` methods in the `WP_Auth0_Options` class.
=> Deprecate WP_Auth0_Options connection methods

WP_Auth0.php, lib/WP_Auth0_Api_Operations.php, lib/initial-setup/WP_Auth0_InitialSetup_Rules.php
Deprecation docblocks and error triggering for unused methods in the `WP_Auth0_Api_Operations` and `WP_Auth0` classes. Also moved all deprecated methods to the bottom of the class.
=> Deprecate methods in WP_Auth0_Api_Operations and related ones in WP_Auth0

lib/WP_Auth0_Metrics.php
Deprecation docblocks and error triggering for the unused `WP_Auth0_Metrics` class.
=> Deprecate WP_Auth0_Metrics

.github/PULL_REQUEST_TEMPLATE.md, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Features.php
There has been some general confusion around how to use the ULP with this plugin. This PR moves the setting to be more visible and changes the name to more clearly explain what the setting does. I left a reference from the old setting to the new one to help with UX. 
[Universal Login vs Embedded](https://auth0.com/docs/guides/login/universal-vs-embedded)
No functionality changes so no testing needed.
=> Rename the Auto Login setting to ULP; move to features tab

lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Settings_Section.php, lib/WP_Auth0_Users.php, lib/WP_Auth0_UsersRepo.php
- Deprecated unused `$admin_role` and `$ignore_unverified_email` parameters in the `WP_Auth0_LoginManager` construct method
- Deprecated unused `end_session()` method in the `WP_Auth0_LoginManager` class
- Deprecate `$role` parameter in the `create_user` method in the `WP_Auth0_Users` class
- Deprecate `$access_token`, `$role`, and `$skip_email_verified` parameters in the `create` method of the `WP_Auth0_UsersRepo` class
=> Deprecate unused login methods and props

WP_Auth0.php
Deprecation docblocks and error triggering for the unused `a0_render_message` method in the `WP_Auth0` class.
=> Deprecate a0_render_message method

.gitignore, composer.json, composer.lock, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_EditProfile.php, lib/WP_Auth0_LoginManager.php, lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/initial-setup/WP_Auth0_InitialSetup.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, lib/initial-setup/WP_Auth0_InitialSetup_Migration.php, lib/twitter-api-php/TwitterAPIExchange.php, phpcs-test-ruleset.xml, phpcs.xml.dist, phpunit.xml.dist, tests/testConstantSettings.php, tests/testEmailVerification.php, tests/testLoginManager.php, tests/testUserRepoCreate.php, tests/testWPAuth0Options.php, tests/traits/hookHelpers.php
**This PR does not change plugin functionality.**
- Rename `phpcs-ruleset.xml` → `phpcs.xml.dist` (automatically picked up by PHPCS)
- Add local PHPCS config files to `.gitignore`
- Update coding standard Composer packages
- Adjust Composer scripts
**Note:** I had to run the auto-formatter command to pass CI. I marked all the modified files with a comment if the changes were whitespace only. Non-whitespace changes in [this commit](https://github.com/auth0/wp-auth0/commit/ab381efba151886af8e477cbfd1de20aaafb776d).
- [Configuration feedback](https://github.com/auth0/auth0-PHP/pull/284#issuecomment-418809388) from @jrfnl
=> Update phpcs script and dependent libs

WP_Auth0.php, lib/WP_Auth0_UsersRepo.php, tests/suiteTemplate.php, tests/testRenderForm.php, tests/testUserRepoMeta.php
- Add `wp_slash()` processing before saving the user profile from Auth0
- Simplified get user profile functions in `WP_Auth0.php`
- Add tests to confirm broken behavior and fix
- Add sample test suite `tests/suiteTemplate.php`
- [Reported in the WP support forums](https://wordpress.org/support/topic/get-user_metadata/)
- [StackOverflow fix applied](https://wordpress.stackexchange.com/questions/53336/wordpress-is-stripping-escape-backslashes-from-json-strings-in-post-meta)
Tests were added before changes to confirm all current behavior as well as broken behavior.
=> Fix user profile saving

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_LoginManager.php, lib/api/WP_Auth0_Api_Abstract.php, tests/testApiAbstract.php
- Update `environment` property with `env`
- Replace `WP_Auth0_Api_Client::get_info_headers()` with `WP_Auth0_Api_Abstract::get_info_headers()`
See internal RFC.
=> Update telemetry header

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Api_Operations.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Features.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testAdminFeatures.php, tests/testApiOperations.php, tests/testInitialSetupConsent.php, tests/traits/httpHelpers.php
This fixes a bug that can cause unintended changes to database connection settings when saving a new password policy. Specific changes:
- Add object property checking to `WP_Auth0_Api_Client::update_connection()` to avoid unnecessary payload errors from the server.
- Remove duplicate connection cleanup from `WP_Auth0_Api_Operations::update_wordpress_connection()`
- Return old password policy setting if an API call fails during validation
- Pass entire connection object to the update API call to avoid unintended settings changes in password policy validation and new connection creation
- Add a large number of tests to confirm behavior
- Docblocks to help investigation and refactoring in the future
- [WP forum report](https://wordpress.org/support/topic/db-migration-automaticly-disable-it-se …
=> Fix Connection update over-writing Connection settings.

WP_Auth0.php, lib/WP_Auth0_LoginManager.php, tests/bootstrap.php, tests/testLoginManager.php, tests/testRenderForm.php, tests/traits/optionsHelpers.php
PR #583 did not address all warnings that came from this change. Moving this to an existing method hooked to `login_init` and adding tests for this and all other functionality in the `login_auto` method. 
#583
=> Change logged-in user redirect to login_init hook

composer.json, lib/profile/WP_Auth0_Profile_Change_Password.php, lib/profile/WP_Auth0_Profile_Delete_Data.php, lib/profile/WP_Auth0_Profile_Delete_Mfa.php, tests/testApiChangePassword.php, tests/testProfileChangePassword.php
Add Auth0 password change functionality to WooCommerce edit account + tests. 
[Reported on the WP support forums](https://wordpress.org/support/topic/password-change-issue). 
This PR adds unit tests. It can also be tested manually by:
1. Start with Auth0 and WooCommerce installed and configured
2. Go to the edit account page for WooCommerce (front-end of the site)
3. Attempt to change the password to something invalid; expect a visible warning, no changes made, and an error in the error log
4. Attempt to change the password to something valid; expect the change to complete with no errors
=> Add WooCommerce password change action.

assets/js/edit-user-profile.js
Change `disabled` property for email field on the profile to `readonly` to avoid errors while saving. 
Closes #587
=> Switch email field property to readonly

lib/WP_Auth0_LoginManager.php
Error messages during login should be shown in a helpful way to the enduser.  We want to add further information to the wp-auth0 error message, which are specific for our setup. The filter allows a modification of the shown html, similar to how it is already done for the email verification prompt.
- Changed method die_on_login in class WP_Auth0_LoginManager to apply a filter on the html output.
No tests added & modified.
=> Added filter to allow for changing the output of die_on_login

WP_Auth0.php, lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_CustomDBLib.php, lib/WP_Auth0_DBManager.php, lib/scripts-js/db-get-user.js, lib/scripts-js/db-login.js, tests/testApiOperations.php
This is the first PR in a process to improve the user migration setup process. 
- Move custom DB scripts from PHP string to separate JS file
- Add method to get script file contents with a name
- Updated tests for minor format changes
- Update version number to `3.9.0-beta`
No new tests added, previous tests updated to new format.
=> Move custom DB scripts to separate files

WP_Auth0.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Ip_Check.php, lib/WP_Auth0_Options_Generic.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Generic.php, tests/testIpCheck.php, tests/testWPAuth0DbMigrations.php
- Migration endpoints will always whitelist Auth0 IPs if whitelist filter is turned on.
- IP whitelist setting in wp-admin shows the Auth0 IPs being whitelisted (see screenshot below).
- DB migration to remove default IPs from the migration IP setting.
**Setting shows default IPs**
=> Whitelist Auth0 IPs by default and show in wp-admin

WP_Auth0.php, lib/WP_Auth0_EditProfile.php, lib/api/WP_Auth0_Api_Change_Email.php, lib/profile/WP_Auth0_Profile_Change_Email.php, lib/profile/WP_Auth0_Profile_Change_Password.php, tests/testApiChangeEmail.php, tests/testEditProfile.php, tests/testProfileChangeEmail.php, tests/traits/usersHelper.php
This PR fixes email updates mapping to Auth0 user accounts. 
- Add `WP_Auth0_Api_Change_Email` class to handle API requests for the updated email
- Add `WP_Auth0_Profile_Change_Email` class to handle the hook when an email is updated in the user edit screen or after verification.
- Minor code comment changes in other relevant files. 
[Reported in the WP plugin support forums](https://wordpress.org/support/topic/cant-change-email-using-profile-page/). 
To test:
1. Make sure your Application is set to allow a client credentials grant (this is configured by default and covered in the [configuration documentation](https://auth0.com/docs/cms/wordpress/configuration)).
2. Make sure your user account has been associated to an Auth0 user (if you're logged in as an admin, you should see a **Delete …
=> Fix email update on Auth0

lib/WP_Auth0_Routes.php, tests/testProfileChangeEmail.php, tests/testRoutesLogin.php, tests/testUserRepoCreate.php, tests/traits/usersHelper.php
- Add `WP_Auth0_Options_Generic::reset()` to reset all options back to defaults
- Add dependency injection to `WP_Auth0_Routes` for the `WP_Auth0_Ip_Check` class
- Add error output for migration login route to help with troubleshooting
=> Fix migration login route output and add tests

lib/WP_Auth0_Options_Generic.php, phpcs-compat-ruleset.xml, phpcs.xml.dist, tests/testConstantSettings.php, tests/testWPAuth0Options.php
When [defining a setting value with constant](https://auth0.com/docs/cms/wordpress/configuration#php-constant-setting-storage), the definition must happen before the plugin is loaded (specifically, before `WP_Auth0_Options` is initialized). This PR fixes an issue where the constant value is not used if defined too late (in the theme, typically) but the setting in wp-admin shows that the constant is loaded. 
Closes #569
1. Define a constant `AUTH0_ENV_DOMAIN` in `wp-config.php`
2. Refresh the wp-admin > Auth0 > Settings > Advanced tab 
**Expect (before and after fix)**
- The constant value displayed in the field
- Field is disabled
- A message above the field referencing the constant being used
- Setting to be used where needed (in login, for example)
3. Delete the constant definition in …
=> Fix notice when settings constant is defined too late

lib/admin/WP_Auth0_Admin_Advanced.php, tests/testAdvancedOptionsValidation.php
Allow sibling subdomains and other ports of the same domain in the default redirect URL. 
Internal support request.
=> Allow subdomains in redirect and refactor validation tests

composer.json, lib/WP_Auth0_Routes.php, phpcs.xml.dist, tests/testRoutes.php, tests/testRoutesGetUser.php, tests/testRoutesLogin.php
Simplify how migration endpoints are served and add tests.
=> Refactor migration route handling and add tests

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Settings_Section.php, lib/initial-setup/WP_Auth0_InitialSetup_ConnectionProfile.php, templates/initial-setup/connection_profile.php
- Add a notice on the Setup Wizard and remove the link from the menu if the plugin has already been configured
- Remove `wp-login.php` from callbacks (not used anymore)
=> Remove unnecessary callback; add notice if plugin is already setup

WP_Auth0.php, lib/WP_Auth0_Amplificator.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_SocialAmplification_Widget.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/twitter-api-php/TwitterAPIExchange.php
Removes the Social Amplificator functionality and adds notes to formally deprecate classes. 
This does not introduce any breaking changes, just removes the widgets and options from the admin screens.
=> Remove Social Amplificator functionality

lib/profile/WP_Auth0_Profile_Change_Password.php, tests/testProfileChangePassword.php
Add `wp_unslash` to new password before sending to Auth0. 
[Reported in the WP support forums](https://wordpress.org/support/topic/characters-allowed-in-password/).
=> Fix escaped passwords sent to Auth0

WP_Auth0.php, lib/WP_Auth0_Amplificator.php, lib/WP_Auth0_SocialAmplification_Widget.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/twitter-api-php/TwitterAPIExchange.php
Officially deprecating methods/classes for the Social Amplificator feature. 
Removed in #607
=> Deprecate Social Amplificator classes + methods

lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_CustomDBLib.php
Move `WP_Auth0_CustomDBLib::get_script()` method to `WP_Auth0_Api_Operations`. This method only exists in `master` (added in #592) and has not yet been released.
=> Move get_script method

lib/WP_Auth0_Routes.php, tests/testRoutes.php, tests/testRoutesGetUser.php, tests/testRoutesLogin.php
Changed the OAuth config endpoint to use a function parameter instead of a global to fix a PHP notice in some cases and make for a more clear implementation.
=> Fix PHP notice on OAuth config endpoint

lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, tests/testWPAuth0Options.php
Remove the unused "IP Range" setting. This was once used for whitelisting IP addresses for wp-admin but the functionality has not been available for many versions. 
Adjusted existing tests for removed options.
=> Remove unused IP range setting

lib/WP_Auth0_Ip_Check.php, lib/admin/WP_Auth0_Admin_Advanced.php
Docblock deprecation notices for:
- `\WP_Auth0_Ip_Check::init`
- `\WP_Auth0_Ip_Check::check_activate`
- `\WP_Auth0_Ip_Check::validate_ip`
- `\WP_Auth0_Ip_Check::get_ranges`
- `\WP_Auth0_Admin_Advanced::render_ip_range_check`
- `\WP_Auth0_Admin_Advanced::render_ip_ranges`
=> Deprecations for ip_range setting

lib/WP_Auth0_Routes.php, lib/admin/WP_Auth0_Admin_Advanced.php, tests/testOptionLoginRedirect.php, tests/testOptionMigrationWs.php
- Add a check for existing token so it does not get regenerated when the endpoints are turned off, then on again (current behavior is to regenerate without warning, which could unintentionally cause login issues). 
- Add `Content-Type: application/json` header to endpoints that output JSON
**Note:** We added an internal task to add a control to regenerate this token in wp-admin. 
- Adjusted existing tests to follow how this setting is handled
- Unable to add unit tests for header output (script `exit`s, making testing impossible)
=> Fix Migration Token Generation; Add JSON Content-Type header

composer.json, tests/bootstrap.php, tests/classes/WP_Auth0_Test_Case.php, tests/testConstantSettings.php, tests/testCustomDomains.php, tests/testRequiredEmail.php
Test suite changes only:
- Autoload traits and classes for test suite
- Pipe `error_log` output to `/dev/null` instead of `STDOUT`
- Minor composer script changes
No changes to test coverage.
=> Autoload traits and suppress log output in tests

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_Options.php, lib/WP_Auth0_RulesLib.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php, tests/testWPAuth0Options.php
There are currently several settings that attempt to create/activate/deactivate Rules in the Auth0 dashboard:
- Features > Multifactor Authentication Multifactor-Guardian-Do-Not-Rename
- Features > Fullcontact integration Enrich-profile-with-FullContact-Do-Not-Rename
- Features > Store Geolocation Store-Geo-Location-Do-Not-Rename
- Features > Store Zipcode Income Enrich-profile-with-Zipcode-Income-Do-Not-Rename
- Advanced > Link Users with Same Email Account-Linking-Do-Not-Rename
These require a valid API token or a client credentials grant (not implemented for these settings currently) and often fail because the Auth0 state is different than the WP admin one. It also makes changes for the whole tenant rather than just the WP site, which could cause issues.
This PR removes this settings …
=> Replace Rules-based settings with prompt to the dashboard [SDK-474]

lib/admin/WP_Auth0_Admin_Advanced.php
- Change the description of "Custom Signup Fields" to mention that this should be an array of JSON objects rather than a JSON. 
- https://auth0.com/docs/libraries/lock/v11/configuration#additionalsignupfields-array-
- https://auth0.com/docs/cms/wordpress/configuration#advanced
-
=> clarify that custom sign up fields should be an array

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Features.php, tests/testOptionPasswordPolicy.php, tests/testOptionSsoSlo.php
- Remove Auth0 Application update from SSO validation middleware
- Add SSO on to Application created process during setup wizard
- Set Features tab defaults to `int` to match validation
- Remove other deprecated middleware
=> Do not update Auth0 Application when SSO is turned on

lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Features.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testInitialSetupConsent.php, tests/testWPAuth0Options.php
Remove database connection password policy management in the settings panel.
=> Remove password policy admin setting

lib/api/WP_Auth0_Api_Abstract.php, lib/api/WP_Auth0_Api_Client_Credentials.php, lib/profile/WP_Auth0_Profile_Delete_Data.php, lib/profile/WP_Auth0_Profile_Delete_Mfa.php, tests/testApiChangeEmail.php, tests/testApiChangePassword.php, tests/testApiClientCredentials.php, tests/testApiDeleteMfa.php, tests/testApiJobsVerification.php, tests/testInitialSetupConsent.php, tests/testProfileChangePassword.php, tests/traits/httpHelpers.php
- Remove Management API access token validation 
- Store new API tokens and scope in transients
Closes #631
- [Failing tests commit](https://github.com/auth0/wp-auth0/pull/632/commits/56f9c236a26eca97eb003253a191da03790750d5)
- [More failing tests commit](https://github.com/auth0/wp-auth0/pull/632/commits/c1b56f675cc9da00bf9827fc45d289509ab017bd)
- [Functionality changes commit](https://github.com/auth0/wp-auth0/pull/632/commits/61533780e7be345fe18381cfe617b25d8f90d551)
- [Passing tests commit](https://github.com/auth0/wp-auth0/pull/632/commits/c3ba87abcfc54b1d91afa49af6ee2a25c7affb67)
=> Better Management API token handling

lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Appearance.php, tests/testOptionCustomCssJs.php, tests/testWPAuth0Options.php
- New installs will not see the Custom CSS and Custom JS fields, only a message and link to upcoming documentation. 
- Installs without a value saved to these fields will see the same. 
- Installs with a value in either field will see a deprecation message.
=> Remove CSS and JS fields for new installs and ones an without existing value

lib/WP_Auth0_Configure_JWTAUTH.php, lib/admin/WP_Auth0_Admin_Advanced.php, templates/configure-jwt-auth.php, tests/testWPAuth0Options.php
Deprecate all settings related to the WP JWT Auth plugin.
[Removed WP JWT Auth plugin](https://wordpress.org/plugins/wp-jwt-auth/)
=> Deprecate WP JWT Auth plugin configuration

lib/WP_Auth0_Options.php
This PR changes the Universal Login Page setting to be on when the site is first installed. This will not change anything for existing sites.
=> Change ULP setting to be on by default

WP_Auth0.php, lib/WP_Auth0_DBManager.php, lib/admin/WP_Auth0_Admin_Basic.php, tests/testWPAuth0DbMigrations.php
In version 3.5.0 and 3.5.1, a Client Credentials grant was automatically created between the WP site and the Management API to retrieve user data. This could only happen if a valid API access token was already saved in the setting page. This grant is no longer required for the plugin to function properly and uncommon for sites that have been live for longer than the token expiration (24 hours be default). 
The number of sites that could use this automatic update was small to begin with and the number of sites that are running < 3.5.x are down to 8% ([plugin stats](https://wordpress.org/plugins/auth0/advanced/)).
This PR removes the automatic check and attempted fix in preparation for removing the admin-stored API token. Sites that update from < 3.5 will still receive user data via the ID …
=> Remove automatic client grant creation

lib/WP_Auth0_Api_Client.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testInitialSetupConsent.php
- Change the Setup Wizard to no longer store the API token used in preparation for removing the App Token setting. 
- Add TODO comments for deprecations before release.
Continues the work from #637 and #632 to remove the App Token field (use a Client Credentials grant for Management API work and store in a expiring transient).
This can be tested manually by installing the plugin from scratch on a new site. Expect no changes to behavior.
=> Do not store the API token on install

WP_Auth0.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_EditProfile.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php, lib/initial-setup/WP_Auth0_InitialSetup_Connections.php, lib/initial-setup/WP_Auth0_InitialSetup_Migration.php, lib/initial-setup/WP_Auth0_InitialSetup_Rules.php, tests/testConstantSettings.php, tests/testWPAuth0Options.php
This PR removes the API token field. All Management API interaction is handled by a client credentials grant.
=> Remove auth0_app_token setting

WP_Auth0.php, lib/WP_Auth0_WooCommerceOverrides.php
Please describe both what is changing and why this is important. Include:
- Endpoints added, deleted, deprecated, or changed
Changed the overrides for the woocommerce login forms
- Classes and methods added, deleted, deprecated, or changed
Updated the WP_Auth0 main plugin to pass options to the woocommerce overrides class
Updated the woocommerce overrides class to create a login button instead of login form if auto login is enabled.
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
Should mention this in the new docs
Please describe how this can be tested by reviewers. Tests must be added for new functionality and existing tests should complete …
=> add auto-redirect if it is set for woocommerce pages too

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_LoginManager.php, lib/api/WP_Auth0_Api_Abstract.php
Internals change to use `WP_Auth0_Api_Client_Credentials` instead of `WP_Auth0_Api_Client` and use injected class instance in `set_bearer` rather than the global class.
Internal only, no testing changes needed.
=> Replace get_client_token with WP_Auth0_Api_Client_Credentials

assets/js/admin.js, lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Basic.php, tests/bootstrap.php, tests/testOptionMigrationWs.php
Adds a button to generate a new migration token for user migration setups.
- Fixes #620 
- [Pending Docs PR commit](https://github.com/auth0/docs/pull/7384/commits/b432d9a22e9be4d89d1dc6b9d2aa548c7a522252)
[Failed tests for new field and functionality](https://circleci.com/gh/auth0/wp-auth0/453)
**Manual Steps:**
1. Paste the following in `wp-config.php`:
```php
define( 'AUTH0_ENV_MIGRATION_WS',  true );
define( 'AUTH0_ENV_MIGRATION_TOKEN', 'THIS_IS_MY_MIGRATION_TOKEN' );
```
2. Refresh the plugin settings page and see the constant-based settings:
3. Save the settings page
4. Comment out the `AUTH0_ENV_MIGRATION_TOKEN` definition added above
5. Refresh the settings page to see an empty migration token:
6. Click the **Generate New Migration Token** button
7. See the alert message:
8. Click …
=> Add ability to generate a new migration token

WP_Auth0.php, assets/js/edit-user-profile.js, lib/WP_Auth0_EditProfile.php, lib/api/WP_Auth0_Api_Delete_User_Mfa.php, lib/profile/WP_Auth0_Profile_Delete_Data.php, lib/profile/WP_Auth0_Profile_Delete_Mfa.php, tests/testProfileDeleteMfa.php
The **Delete MFA** control on the user profile was not playing nicely with how MFA is deleted. Since we have not had any reports about it, this PR removes the control and adds a link to the user in the Auth0 dashboard where MFA changes can be made directly.
=> Remove Delete MFA control on user profile; add link to user in dashboard

lib/WP_Auth0_Api_Client.php
New installs will now be flagged as OIDC conformant.
[OIDC Conformant applications](https://auth0.com/docs/api-auth/intro#legacy-vs-new)
=> Set OIDC conformant for new installs

composer.json, lib/WP_Auth0_Amplificator.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Configure_JWTAUTH.php, lib/WP_Auth0_CustomDBLib.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Embed_Widget.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_Metrics.php, lib/WP_Auth0_Referer_Check.php, lib/WP_Auth0_SocialAmplification_Widget.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Dashboard.php, lib/admin/WP_Auth0_Admin_Features.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Age.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Gender.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Generic.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_IdP.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Income.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Location.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Plugins_Signups.php, lib/dashboard-widgets/WP_Auth0_Dashboard_Widgets.php, lib/initial-setup/WP_Auth0_InitialSetup.php, lib/initial-setup/WP_Auth0_InitialSetup_Migration.php, lib/initial-setup/WP_Auth0_InitialSetup_Rules.php, lib/initial-setup/WP_Auth0_InitialSetup_Signup.php, lib/twitter-api-php/TwitterAPIExchange.php
- Add translation issue scan to Composer scripts: `composer phpcs-i18n`
- Fix all issues from the scan above
- Add `phpcs:ignoreFile` directives to deprecated classes to skip scans for that file
[WordPress i18n guidelines](https://codex.wordpress.org/I18n_for_WordPress_Developers)
=> Fix all translate-able text issues

lib/WP_Auth0_Api_Client.php, templates/initial-setup/connection_profile.php, tests/testApiClient.php
Change the Management API scopes displayed during setup.
[Docs PR commit](https://github.com/auth0/docs/pull/7384/commits/28012e48126ecd91caf92549b7ef3da9fb2d0651)
=> Change API scopes needed in the Setup Wizard

lib/WP_Auth0_Configure_JWTAUTH.php, lib/WP_Auth0_UsersRepo.php
This PR deprecates the following methods:
- `WP_Auth0_UsersRepo::init()` - still used but will be removed in the next major.
- `WP_Auth0_UsersRepo::getUser()` - no longer used
- `WP_Auth0_UsersRepo::tokenHasRequiredScopes()` - no longer used
=> Deprecate WP_Auth0_UsersRepo methods

lib/WP_Auth0_RulesLib.php, lib/WP_Auth0_Settings_Section.php
This PR deprecates the `WP_Auth0_RulesLib` class as it is no longer used.
=> Deprecate WP_Auth0_RulesLib class

lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Routes.php
This PR deprecates the following methods:
- `WP_Auth0_Lock10_Options::get_sso()` - No longer used.
- `WP_Auth0_Lock10_Options::get_client_id()` - No longer used.
=> Deprecate WP_Auth0_Lock10_Options class

lib/api/WP_Auth0_Api_Delete_User_Mfa.php, lib/profile/WP_Auth0_Profile_Delete_Mfa.php
This PR deprecates the following classes:
- `WP_Auth0_Profile_Delete_Mfa` - No longer used, MFA must be administered in the Auth0 Dashboard.
- `WP_Auth0_Api_Delete_User_Mfa` - No longer used, supporting class for above.
=> Deprecate WP_Auth0_Profile_Delete_Mfa and WP_Auth0_Api_Delete_User_Mfa

lib/WP_Auth0_LoginManager.php
This PR deprecates the following methods:
- `WP_Auth0_LoginManager::init()` - Next major will move `add_action` calls to global functions.
- `WP_Auth0_LoginManager::auth0_sso_footer()` - No longer used.
- `WP_Auth0_LoginManager:: auth0_singlelogout_footer()` - No longer used.
=> Deprecate WP_Auth0_LoginManager methods

lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_Configure_JWTAUTH.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_EditProfile.php, lib/WP_Auth0_Email_Verification.php, lib/WP_Auth0_ErrorLog.php, lib/WP_Auth0_Export_Users.php, lib/WP_Auth0_Import_Settings.php
This PR deprecates the following methods:
- `WP_Auth0_Api_Operations:: update_wordpress_connection()` - No longer used.
- `WP_Auth0_Api_Operations:: toggle_rule()` - No longer used.
Added a few more `TODO` comments and `@codeCoverageIgnore` annotations
=> Deprecate WP_Auth0_Api_Operations methods

lib/admin/WP_Auth0_Admin_Features.php
This PR deprecates the `\WP_Auth0_Admin_Features::render_sso()` method, removed in the next major.
=> Deprecations for render_sso method

WP_Auth0.php, functions.php, templates/back-to-auth0.php, templates/initial-setup/connection_profile.php, templates/initial-setup/enterprise_connections.php, templates/settings.php, tests/testWPAuth0Options.php
Add `wp_auth0_get_option()` function for getting option values. This will make it easier for plugins/themes that extend the plugin.
=> Add wp_auth0_get_option function to get option values

lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Features.php, phpcs-test-ruleset.xml, templates/login-form.php, tests/testLoginManagerInitAuth0.php
- Redirect to the Auth0 logout link when attempting to re-login after a callback error occurs. This will avoid loops caused by SSO. 
- Clear the WP session when a callback error occurs.
- Set single logout on by default (to avoid login loops when ULP is on)
- Reorder options on the Features tab.
=> Redirect from Auth0 on callback error

lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_Options_Generic.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Dashboard.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php, tests/testConstantSettings.php, tests/testWPAuth0Options.php
Official deprecation for the `WP_Auth0_Options_Generic` parent class. All active methods will be merged into `WP_Auth0_Options` child class in the next major.
=> Deprecate WP_Auth0_Options_Generic

lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options_Generic.php, tests/testConstantSettings.php, tests/testWPAuth0DbMigrations.php, tests/testWPAuth0Options.php
This PR fixes 2 issues that surface during database migrations. 
- Fix updating options removes constant-set values from memory
- Fix getting options replacing empty values with defaults
- Update database migrations to batch-save new options
- Add `remove()` method to remove option keys from memory and database 
**See commit log for commits with failing tests.**
=> Fix options overwriting with defaults and removing constant values on update

lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php
- Fix a PHP notice that occurs when there is no `language_dictionary` field during settings save
- Remove validation for removed settings
=> Fix PHP notice when there is no language_dictionary

lib/WP_Auth0_Routes.php, lib/WP_Auth0_UsersRepo.php, lib/profile/WP_Auth0_Profile_Change_Email.php, tests/testProfileChangeEmail.php, tests/testRoutesGetUser.php, tests/testRoutesLogin.php, tests/testUserRepoMeta.php
Fixes an issue where sites using a custom database could not update user email addresses from the WordPress profile. 
[WP.org support forum thread](https://wordpress.org/support/topic/cant-change-email-using-profile-page-once-again/)
[Tests for user meta changes](https://github.com/auth0/wp-auth0/pull/674/commits/b2e62c27058486b01631ebf30399d3d489344f14)
[Tests for email update flag](https://github.com/auth0/wp-auth0/pull/674/commits/2f193aa13730c4988b7119fdee2d4ab08c89fb78)
[Tests for get user route](https://github.com/auth0/wp-auth0/pull/674/commits/0e215dee9ea5313b897a84842b87e4eeb821067b)
=> Check for email update in migration-ws-get-user endpoint

lib/WP_Auth0_LoginManager.php, tests/testLoginManagerLogout.php
Fix logout redirect if the plugin is not ready (no domain name or client ID)
=> Fix Auth0 logout redirect

lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testInitialSetupConsent.php
This PR fixes an issue when a migration token exists (set in a constant) but does not get saved to the custom DB scripts.
=> Use existing migration token during setup

.circleci/config.yml, composer.json, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_LoginManager.php, lib/api/WP_Auth0_Api_Abstract.php, lib/api/WP_Auth0_Api_Exchange_Code.php, lib/api/WP_Auth0_Api_Get_User.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testApiAbstract.php, tests/testApiChangeEmail.php, tests/testApiClientCredentials.php, tests/testApiGetUser.php, tests/testInitialSetupConsentExchangeCode.php, tests/testLoginManagerRedirectLogin.php, tests/traits/httpHelpers.php
This PR refactors the auth code login flow to use the new API abstract.
**Reviewer notes:**
~650 lines of tests added, see below for specific changes.
- [Commit for tests added to cover functionality before changes](https://github.com/auth0/wp-auth0/pull/678/commits/3b6c96c4b333d82853329f028d1b4f737217f805)
- [Update tests to fail for missing new functionality](https://github.com/auth0/wp-auth0/pull/678/commits/408517d55a186e56bb799324f7a13d4afc4b3cd3)
- [Most functionality changes here](https://github.com/auth0/wp-auth0/pull/678/commits/f0cda712afebbbdf35e4e25b6e57d5300448f173)
- [Somewhat unrelated change to remove client grant scopes requested (found while testing)](https://github.com/auth0/wp-auth0/pull/678/commits/f3485e7574df6742b3157552556ec6319908782a)
=> Refactor Auth Code login and add tests

WP_Auth0.php, composer.json, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_Lock_Options.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Appearance.php, readme.txt, templates/a0-widget-setup-form.php, tests/bootstrap.php, tests/testAdminAppearanceValidation.php, tests/testLockOptions.php, tests/testWPAuth0DbMigrations.php, tests/testWPAuth0Options.php
- Remove small social button option
- Fix Embedded setting validation
[Lock removing small social button config option](https://github.com/auth0/lock/pull/1637)
=> Remove small social icons

lib/WP_Auth0_Api_Operations.php, lib/scripts-js/db-get-user.js, lib/scripts-js/db-login.js, tests/testApiOperations.php
This PR adds name-spacing for the user ID when using a custom database. It also moves configuration data (URL, namespace, and migration token) to the configuration manager. This will change how new user migration sites work but will not break or change existing ones. 
- [WordPress support forum thread](https://wordpress.org/support/topic/important-error-mixing-identities/)
- [Docs PR commit](https://github.com/auth0/docs/pull/7594/commits/bb620bbc459d99f6ad51c5e4effcd1605f0fb88c)
This can be tested by:
1. Installing this version of the plugin from scratch
2. Running the Setup Wizard for user migrations ([docs](https://auth0.com/docs/cms/wordpress/installation#option-2-user-migration-setup))
3. Completing the process and logging in to create the Auth0 user
4. Attempting a password change …
=> Namespace user IDs and use DB configuration for new user migration installs

lib/admin/WP_Auth0_Admin_Appearance.php
Deprecates `WP_Auth0_Admin_Appearance::render_social_big_buttons()` (no longer used going forward).
=> [TINY] Deprecate Render Big Social Buttons method

lib/WP_Auth0_Api_Client.php
Deprecates:
- `WP_Auth0_Api_Client::get_token()` (use `WP_Auth0_Api_Client_Credentials` instead)
- `WP_Auth0_Api_Client::get_user()` (use `WP_Auth0_Api_Get_User` instead)
=> Deprecate WP_Auth0_Api_Client methods

WP_Auth0.php, tests/testWPAuth0DbMigrations.php, tests/testWPAuth0Helpers.php
- Update Lock to 11.16
- Translate plugin link text
- Remove plugin link to error log
[Lock v11.16 release](https://github.com/auth0/lock/releases/tag/v11.16.0)
=> Translate plugin links and remove error log

WP_Auth0.php, assets/css/login.css, functions.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, phpcs-test-ruleset.xml, tests/testEditProfile.php, tests/testFunctionIsCurrentLoginAction.php, tests/testFunctionLoginOverrideUrl.php, tests/testLoginManager.php, tests/testOptionCanShowWpLogin.php, tests/testProfileChangeEmail.php, tests/testProfileChangePassword.php, tests/testProfileDeleteData.php, tests/testRenderForm.php, tests/testWPAuth0Options.php, tests/testWpLoginHooks.php, tests/traits/hookHelpers.php
Summary of changes:
- Makes password reset process function end-to-end without ULP redirect or embedded form showing
- Stops all WP core login form requests when WP login is set to "never"
- Adds `wp_auth0_is_current_login_action()` to check if the current request is wp-login.php and if the user is attempting a specific action.
- Adds `wp_auth0_login_override_url()` to build a WordPress login override URL based on current settings.
- Adds `wp_auth0_can_show_wp_login_form()` to check if the core WP login form can be shown.
Whether using ULP or not, if navigating to a core WP login page and the WordPress Login Enabled is anything but "Never," you should be able to login (with feedback if login was incorrect) and reset password (with feedback if user not found).
=> Improve WordPress core login override for security and UX

lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_LoginManager.php, tests/testLockOptions.php, tests/testLoginManagerRedirectLogin.php
- Adds `auth0_lock_options` filter to modify Lock options before using
- Renames unreleased `wp_auth0_use_management_api_for_userinfo` to `auth0_use_management_api_for_userinfo` for consistency.
[Docs PR to add new filter, change previous](https://github.com/auth0/docs/pull/7594/commits/07a2f5f52f34ae6f5e4873bd683f8d762adb0cab)
=> Add auth0_lock_options filter

lib/WP_Auth0_Options.php
Deprecates `WP_Auth0_Options::can_show_wp_login_form()`
=> Deprecate WP_Auth0_Options::can_show_wp_login_form()

WP_Auth0.php, functions.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_WooCommerceOverrides.php, phpcs-test-ruleset.xml, templates/login-form.php, tests/testFunctionCanShowWpLoginForm.php, tests/testFunctionIsCurrentLoginAction.php
Add a query var during Auth0 login to indicate the status of the process globally. This allows for the VIP MFA form to show instead of a redirect (ULP) or Auth0 form showing (embedded). Also switches all uses of `WP_Auth0_Options::Instance()->can_show_wp_login_form()` to `wp_auth0_can_show_wp_login_form()`.
Closes #687
=> Fix VIP Go MFA screen

lib/WP_Auth0_Id_Token_Validator.php, tests/testFunctionCanShowWpLoginForm.php, tests/testIdTokenValidator.php
Change the not-yet-released JWT filter name from `wp_auth0_jwt_leeway` to `auth0_jwt_leeway`
=> Change JWT leeway filter name and add tests

lib/WP_Auth0_Api_Operations.php, lib/WP_Auth0_Routes.php, lib/api/WP_Auth0_Api_Change_Email.php, lib/scripts-js/db-get-user.js, lib/scripts-js/db-login.js, tests/testApiChangeEmail.php, tests/testApiOperations.php, tests/testRoutesGetUser.php
- Change the namespace used when creating a new custom DB connection
- Remove the check for username on the get user endpoint
- Add `client_id` to the update user API call
=> Fix migration namespace and callback

CHANGELOG.md, lib/WP_Auth0_Routes.php
Fixes an issue were accessing a page with `auth0` in the path triggered a redirect to the callback URL, which causes an Invalid State error.
Fixes #351
=> Fix auth0 in paths triggering callback

.circleci/config.yml, functions.php, tests/testFunctionCanShowWpLoginForm.php
Content with a password is getting redirected to the ULP. 
To manually test before the fix:
1. Turn on **Auth0 > Settings > Features > Universal Login Page**
2. Create a new post or page
3. Set Visibility to Password Protected
4. View the post or page
5. Enter the password and submit
6. Redirected to the ULP (bad)
7. Apply the fix
8. Try steps 4 and 5 above
9. See the password-protected content
=> Fix post passwords getting redirected

lib/WP_Auth0_Ip_Check.php, lib/admin/WP_Auth0_Admin_Advanced.php, tests/testIpCheck.php, tests/testOptionMigrationIps.php
- Add new Auth0 incoming IP addresses to fix migration route filters
- Fix IP address validation to exclude duplicate, empty values, and IPs already whitelisted
[Current Auth0 IP address list](https://auth0.com/docs/guides/ip-whitelist)
=> Add new Auth0 IPs; do not save duplicate or whitelisted IPs

composer.json, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Generic.php, templates/initial-setup/connection_profile.php, tests/testAdminBasicValidation.php, tests/testConstantSettings.php, tests/testOptionClientId.php, tests/testOptionClientSecret.php, tests/testOptionDomain.php
- Fix `password` field types (client secret and API token) triggering password managers
- Add empty required field error styles
- Add validation/sanitization for domain, custom domain, client secret, and token algorithm fields
**Note to reviewers:** bulk of the additions here are missing tests
Internal support request. 
Please describe how this can be tested by reviewers. Tests must be added for new functionality and existing tests should complete without errors.
=> Fix sensitive field handling; add Basic settings tab validations

lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, tests/testOptionLockCdn.php
Fixed an issue where the CDN URL is validated while being hidden, causing the settings page to fail while saving silently.
Internal support request.
=> Change CDN URL field type

lib/WP_Auth0_LoginManager.php, tests/testLoginManagerInitAuth0.php
Add checking for state in other PHP globals in case `$_REQUEST` is not set.
=> Add check for GET and POST globals for state validation

lib/WP_Auth0_LoginManager.php, tests/classes/WP_Auth0_Test_Case.php, tests/testLoginManagerInitAuth0.php, tests/traits/wpDieHelper.php
Fix state checking to look in the correct global (`$_GET` for auth code, `$_POST` for implicit) instead of query var or `$_REQUEST`.
Reverts #707
=> Check state in specific global based on callback type

WP_Auth0.php, lib/WP_Auth0_WooCommerceOverrides.php, tests/testWoocommerceOverrides.php
**This is a potential (though unlikely) breaking change for developers!** 
- **BREAKING:** Remove deprecated `\WP_Auth0_WooCommerceOverrides:: init()` method
- **BREAKING:** Enforce `WP_Auth0_WooCommerceOverrides` constructor accepts a `WP_Auth0_Options` instance
- Switch `woocommerce_checkout_login_message` hooked function from `\WP_Auth0_WooCommerceOverrides::override_woocommerce_checkout_login_form()` to new `wp_auth0_filter_woocommerce_checkout_login_message()`
- Switch `woocommerce_before_customer_login_form ` hooked function from `\WP_Auth0_WooCommerceOverrides::override_woocommerce_login_form()` to new `wp_auth0_filter_woocommerce_before_customer_login_form()`
- Add a check for plugin readiness
=> Move WooCommerce hooks to global functions and remove init method

lib/WP_Auth0_Users.php
Add filter `wpa0_user_data`  to allow customizing user data before creating WP_User because I would like to separate `display_name` from `username`. The current implementation hardcodes the WordPress `user_login` and `display_name` to come from the Auth0 `username`. However, in many cases, those are separated based on naming style in Japan.
There is no reference. only this PR.
=> Add wpa0_user_data filter before creating WP_User

lib/WP_Auth0_LoginManager.php, tests/testLoginManager.php, tests/testLoginManagerAuthParams.php
- Move filter `auth0_authorize_url_params` before state is generated and decoded
- Add filter `auth0_authorize_state` to modify state contents before decoding
=> Update auth params method to add filters

lib/WP_Auth0_Api_Client.php
**This is a potential breaking change for developers!**
Remove all deprecated `WP_Auth0_Api_Client` methods:
- `get_info_headers()`
- `get_token()`
- `get_client_token()`
- `get_user_info()`
- `get_client()`
- `update_client()`
- `create_rule()`
- `delete_rule()`
- `get_connection()`
- `update_user()`
- `GetConsentScopestoShow()`
- `update_guardian()`
- `ro()`
- `validate_user_token()`
- `search_users()`
- `resend_verification_email()`
- `create_user()`
- `search_clients()`
- `get_current_user()`
- `delete_connection()`
- `delete_user_mfa()`
- `change_password()`
- `link_users()`
**Note to reviewers:** All additions in the changeset are docblocks.
=> Remove deprecated WP_Auth0_Api_Client methods

.circleci/config.yml, bin/install-wp-tests.sh, composer.json, lib/WP_Auth0_Nonce_Handler.php, lib/api/WP_Auth0_Api_Refresh_Access_Token.php, phpcs-compat-ruleset.xml, phpcs.xml.dist, readme.txt
Update minimum PHP version to 7.0
=> Update minimum PHP to 7.0 and WP to 4.9

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Lock10_Options.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, tests/testApiClient.php, tests/testLockOptions.php, tests/testLoginManagerAuthParams.php, tests/testWPAuth0DbMigrations.php, tests/testWPAuth0Options.php
Remove the Implicit Login Flow option. The plugin will switch to asking for a user-scoped Management API token in a future PR. 
**Removed the following public methods:**
- `WP_Auth0_Lock10_Options::get_code_callback_url()`
- `WP_Auth0_Lock10_Options::get_implicit_callback_url()`
- `WP_Auth0_Lock10_Options::get_auth0_implicit_workflow()`
- `WP_Auth0_Lock10_Options::get_auth0_implicit_workflow()`
- `WP_Auth0_LoginManager::implicit_login()`
- `WP_Auth0_Admin_Advanced::render_auth0_implicit_workflow()`
=> Remove implicit login flow

CHANGELOG.md, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Basic.php, tests/testAdminBasicValidation.php, tests/testOptionMigrationWs.php, tests/testWPAuth0DbMigrations.php, tests/testWPAuth0Options.php
This removed the Client Secret Encoded option. If your WordPress site was using an encoded Client Secret (unlikely but it will say on the Application settings page in Auth0), you'll need to regenerate one in the Auth0 dashboard and save it in wp-admin > Auth0 > Settings > Basic > Client Secret.
Removes `WP_Auth0_Admin_Basic::render_client_secret_b64_encoded()`.
=> Remove client_secret_b64_encoded setting

WP_Auth0.php, lib/WP_Auth0_Routes.php, tests/testRoutes.php, tests/testRoutesGetUser.php, tests/testRoutesLogin.php
Move `WP_Auth0_Routes::init()` method to `wp_auth0_custom_requests()`
=> Move WP_Auth0_Routes initialize method to function

WP_Auth0.php, lib/WP_Auth0_DBManager.php, tests/testWPAuth0DbMigrations.php
- Remove upgrade process for plugin versions < 3.1.6 (no tenants reporting this version)
- Move `WP_Auth0_DBManager::init()` functionality to `wp_auth0_db_check_update()`
- Remove `WP_Auth0_DBManager::init()` 
- Remove `WP_Auth0_DBManager::check_update()` 
- Remove `WP_Auth0_DBManager::notice_failed_client_grant()` 
- Remove `WP_Auth0_DBManager::notice_successful_client_grant()` 
- Remove `WP_Auth0_DBManager::notice_successful_grant_types()` 
- Remove `WP_Auth0_DBManager::migrate_users_data()`
=> Remove deprecated from WP_Auth0_DBManager and move init to function

WP_Auth0.php, lib/WP_Auth0_Email_Verification.php, tests/testEmailVerification.php
- Remove `WP_Auth0_Email_Verification::init()`
- Remove `WP_Auth0_Email_Verification::resend_verification_email()` (merged with `wp_auth0_ajax_resend_verification_email()`)
- Remove `WP_Auth0_Email_Verification::ajax_resend_email()`
=> Remove deprecated from email verification

WP_Auth0.php, lib/WP_Auth0_Users.php, lib/profile/WP_Auth0_Profile_Change_Password.php, tests/classes/WP_Auth0_Test_Case.php, tests/testApiGetUser.php, tests/testEmailVerification.php, tests/testLoginManagerRedirectLogin.php, tests/testProfileChangePassword.php
- Remove `$role` parameter from `WP_Auth0_Users::create_user()`
- Remove `WP_Auth0_Profile_Change_Password::init()`
=> Remove deprecated from User and Change Password

WP_Auth0.php, functions.php, lib/WP_Auth0_UsersRepo.php, lib/profile/WP_Auth0_Profile_Change_Email.php, lib/profile/WP_Auth0_Profile_Delete_Data.php, tests/testProfileChangeEmail.php, tests/testProfileDeleteData.php, tests/testUserMeta.php, tests/testUserRepoMeta.php
- Change `WP_Auth0_UsersRepo::delete_auth0_object()` to `wp_auth0_delete_auth0_object()`
- Remove `WP_Auth0_Profile_Change_Email::init()` 
- Remove `WP_Auth0_UsersRepo` dependency from `WP_Auth0_Profile_Delete_Data` constructor 
- Remove `WP_Auth0_Profile_Delete_Data::init()`
=> Move actions from methods to functions for profile delete and change email

WP_Auth0.php, assets/js/admin.js, functions.php, lib/WP_Auth0_Import_Settings.php, lib/admin/WP_Auth0_Admin.php, templates/import_settings.php, tests/testFunctionIsAdminPage.php, tests/testImportExportSettings.php
- Remove ability to upload an import JSON file to avoid potential security problems and additional site configuration (JSON files are not allowed by default in WP).
- Move `WP_Auth0_Import_Settings::init()` actions to functions.
- Remove `WP_Auth0_Import_Settings::show_error()`
- Add explicit checks for admin capabilities on import and export settings pages.
=> Remove deprecated from import settings

WP_Auth0.php
Add absolute path constant to included files.
https://wordpress.org/support/topic/call-to-functions-php/
=> Fix include path for functions file

.circleci/config.yml, WP_Auth0.php, bin/install-wp-tests.sh
Fix functions.php include path.
[WP.org support thread](https://wordpress.org/support/topic/call-to-functions-php/)
=> Add path to functions.php include

composer.json, functions.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Nonce_Handler.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, tests/classes/WP_Auth0_Test_Case.php, tests/testFunctionUsesSecureCallback.php, tests/testNonceHandler.php, tests/testWPAuth0Options.php
- Add SameSite=None and Secure attribute to nonce and state cookies when implicit mode is turned on
- Add notice for implicit mode deprecation and HTTPS check if this setting is turned on
[Web.dev: SameSite cookies explained](https://web.dev/samesite-cookies-explained/)
=> Patch samesite for implicit

lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_ErrorLog.php, tests/testErrorLog.php
- Remove all calls to PHP core `error_log`
- Add `auth0_insert_error` action to allow additional error handling
=> Remove error_log calls and add auth0_insert_error action

lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, templates/auth0-login-form.php, tests/testWPAuth0DbMigrations.php, tests/testWPAuth0Options.php
Remove database-stored extra signup fields setting for the embedded login form. Custom fields must now be added by enqueueing a JS file before the embedded form loads:
```php
function namespace_login_enqueue_scripts() {
// This example assumes that this file is loaded from your theme.
wp_enqueue_script( 'lock-signup-fields', get_stylesheet_directory_uri() . '/assets/js/lock-signup-fields.js' );
}
add_action( 'login_enqueue_scripts', 'namespace_login_enqueue_scripts' );
```
... that defines a specific global variable `wpAuth0LockGlobalFields` with the signup fields defined:
```js
// lock-signup-fields.js
var wpAuth0LockGlobalFields = [
{
name: "full_name",
placeholder: "your full name",
validator: function(address) {
return {
valid: address.length >= 10,
hint: "Must have 10 or more chars" …
```
=> Remove custom signup fields setting

WP_Auth0.php, lib/WP_Auth0_LoginManager.php, lib/initial-setup/WP_Auth0_InitialSetup_AdminUser.php, lib/initial-setup/WP_Auth0_InitialSetup_ConnectionProfile.php, lib/initial-setup/WP_Auth0_InitialSetup_Connections.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testSafeRedirects.php
Change all instances of `wp_redirect` to `wp_safe_redirect` and filter necessary hosts.
https://developer.wordpress.org/reference/functions/wp_safe_redirect/
https://developer.wordpress.org/reference/hooks/allowed_redirect_hosts/
=> Change all redirects to wp_safe_redirect

composer.json, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Generic.php, lib/initial-setup/WP_Auth0_InitialSetup_Consent.php, tests/testLoginManagerRedirectLogin.php, tests/testOptionMigrationWs.php, tests/testRequiredEmail.php, tests/testRoutesGetUser.php, tests/testRoutesLogin.php, tests/testUserRepoCreate.php
- Normalize settings validation for the Advanced tab
- Normalize defaults for the Advanced tab
- Remove `WP_Auth0_Admin_Advanced->render_auto_login()`
[WP guidance on sanitization and escaping](https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/)
=> Adding advanced setting validation; normalize values throughout

lib/WP_Auth0_LoginManager.php, lib/token-verifier/WP_Auth0_AsymmetricVerifier.php, lib/token-verifier/WP_Auth0_JwksFetcher.php, tests/testApiGetJwks.php, tests/testJwksFetcher.php, tests/testLoginManagerRedirectLogin.php, tests/testOptionMigrationWs.php, tests/testRoutesGetUser.php, tests/testRoutesLogin.php, tests/traits/tokenHelper.php
Add `WP_Auth0_JwksFetcher->getKey()` for use in `WP_Auth0_AsymmetricVerifier` to fetch a new JWKS when an incoming token KID is not found in the cached set. This library doesn't accept arbitrary requests that involve token validation and the endpoint that validates tokens is protected by a `state` parameter so there is not much of a risk of invalid `kid` spamming.
SDK-1224
=> Add ability to break cache if RS256 ID token kid is not found

functions.php, lib/WP_Auth0_Api_Client.php, lib/WP_Auth0_Import_Settings.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/initial-setup/WP_Auth0_InitialSetup.php, tests/testOptionWle.php, tests/testWPAuth0Options.php
- Normalize settings validation for the Basic tab
- Normalize defaults for the Basic tab
- Remove `WP_Auth0_Admin_Basic->wle_validation()`
[WP guidance on sanitization and escaping](https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/)
=> Update Basic settings validation and defaults

WP_Auth0.php, lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Lock.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Appearance.php, tests/testAdminAppearanceValidation.php, tests/testOptionLockCdn.php, tests/testWPAuth0DbMigrations.php
- Normalize settings validation for the Embedded tab
- Normalize defaults for the Embedded tab
- Update Lock from `11.16.x` to `11.21.x`
- Update Auth0.js from `9.10` to `9.12`
[WP guidance on sanitization and escaping](https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/)
=> Update Embedded settings validation and defaults

lib/WP_Auth0_Embed_Widget.php, lib/WP_Auth0_Import_Settings.php, lib/admin/WP_Auth0_Admin.php, lib/admin/WP_Auth0_Admin_Advanced.php, lib/admin/WP_Auth0_Admin_Appearance.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/admin/WP_Auth0_Admin_Features.php, lib/admin/WP_Auth0_Admin_Generic.php, templates/import_settings.php, templates/settings.php, tests/testAdminAppearanceValidation.php, tests/testAdminBasicValidation.php, tests/testAdminSettingsValidationPath.php, tests/testImportExportSettings.php, tests/testOptionLockCdn.php, tests/testOptionLoginRedirect.php, tests/testOptionMigrationIps.php, tests/testOptionMigrationWs.php, tests/testOptionSlo.php, tests/testOptionWle.php, tests/testRequiredEmail.php, tests/testWPAuth0Options.php
- Add validation to imported settings JSON
- Change the following validation methods to accept only the new options array as a first parameter; existing saved options values are used as fallbacks:
- `WP_Auth0_Admin_Advanced->basic_validation()`
- `WP_Auth0_Admin_Advanced->migration_ws_validation()`
- `WP_Auth0_Admin_Advanced->migration_ips_validation()`
- `WP_Auth0_Admin_Appearance->basic_validation()`
- `WP_Auth0_Admin_Basic->basic_validation()`
- `WP_Auth0_Admin_Features->basic_validation()`
- Rename `WP_Auth0_Admin_Advanced::loginredirection_validation()` to `WP_Auth0_Admin_Advanced->validate_login_redirect()` and changed the signature to accept the new and previous values instead of arrays.
**Note to reviewers:** vast majority of the changes here are renaming and changing the method …
=> Add settings validation to import

lib/WP_Auth0_DBManager.php, lib/WP_Auth0_Options.php, lib/WP_Auth0_Routes.php, lib/admin/WP_Auth0_Admin_Advanced.php, tests/testOptionMigrationWs.php, tests/testRoutesGetUser.php, tests/testRoutesLogin.php, tests/testWPAuth0Options.php
Remove JWT JTI check for migration routes. Token is checked against stored value so token can be opaque. This will only affect sites that generated their own migration token as a JWT and stored a different token in the migration route than in the WordPress site (which would be a really odd thing to do).
=> Remove migration JWT JTI check

functions.php, lib/WP_Auth0_Embed_Widget.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_UsersRepo.php, lib/WP_Auth0_WooCommerceOverrides.php, lib/token-verifier/WP_Auth0_AsymmetricVerifier.php, lib/token-verifier/WP_Auth0_SignatureVerifier.php
By submitting a PR to this repository, I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
@joshcanhelp Started static analysis by @phpstan
https://packagist.org/packages/szepeviktor/phpstan-wordpress
Please consider using PHPStan on at least Level 4.
`phpstan.neon.dist`
```yaml
#$ composer require --dev szepeviktor/phpstan-wordpress
#$ vendor/bin/phpstan analyze -l 3
includes:
- vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
level: max
inferPrivatePropertyTypeFromConstructor: true
autoload_files:
- functions.php
- WP_Auth0.php
paths:
- functions.php
- lib/
ignoreErrors:
- '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
```
=> PHPStan Level 2 fixes

WP_Auth0.php, composer.json
=> Load ourselves with Composer autoloader

.circleci/config.yml, composer.json
Shocked 😲 me in #787 
Closes #787
=> Validate composer config

WP_Auth0.php
In 4.0.0 the "[auth0]" shortcode no longer accepts parameters (i.e "redirect_to"), this looks like it was an accidental bug introduced during a rewrite.
Verified locally that the redirect_to shortcode now works. Also compared to v3.11 to be sure that this used to be supported.
=> Pass shortcode atts to the handler

lib/token-verifier/WP_Auth0_JwksFetcher.php, tests/testJwksFetcher.php
Use the custom domain for the JWKS instead of the main domain. 
Closes #790
=> Fix custom domain not being used in JWKS

.circleci/config.yml, WP_Auth0.php, readme.txt
Raise authentication processing priority from default `10` to `1` (lower === earlier). 
Fixes ESD-8010
=> Raise priority of authentication processing

lib/profile/WP_Auth0_Profile_Change_Email.php
Switch `remove_action()` and subsequent `add_action()` call to remove/add the function that calls this method, rather than the method itself.
Fixes #800. 
Waiting on #803 for CI fixes
=> Fix potential infinite loop on email update

lib/WP_Auth0_Lock.php
- deps is an array
- do not add WP core version to lock.js URL
This is PHPStan Level 5
=> Fix enqueued scripts

examples/auth0_before_login.php, lib/WP_Auth0_LoginManager.php
There are situations in which we want to check whether the user is authorized to access a wordpress website based on the info passed by Auth0 (contained in app_metadata or user_metadata)
This PR aim is for this info to be available in the auth0_before_login action
Because at that point the user is already logged in. 
Letting the user login and then rejecting him is not ideal, especially if we want to show a custom error page
=> Pass user info to auth0_before_login action

composer.json
This PR includes minor changes to our composer.json that;
- Allows installations via [wpackagist](https://wpackagist.org/)
- Updates our authors manifest to match our other PHP libraries
- Adds keywords to improve package discovery
- Restructures order of composer manifest to match our other PHP libraries
There are no functional or necessary test changes in this PR.
=> Allow Composer installations w/ wpackagist

LICENSE
Updates our LICENSE file to follow the same standard MIT format as our other libraries to resolve FOSSA and GitHub parsing issues.
=> chore: Use standard MIT license format

WP_Auth0.php
Enables publishing this plugin to Packagist. Packagist installs will use the project `vendor` directory rather than requiring the plugin to bundle it.
- Issue #823
=> Support installation via Packagist

README.md, WP_Auth0.php, lib/WP_Auth0_LoginManager.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Basic.php, lib/api/WP_Auth0_Api_Abstract.php, lib/token-verifier/WP_Auth0_IdTokenVerifier.php, tests/testApiAbstract.php, tests/testIdTokenVerifier.php, tests/testOptionOrganization.php, tests/testSymmetricVerifier.php, tests/testWPAuth0Helpers.php, tests/testWPAuth0Options.php
This PR includes changes necessary for the WordPress plugin to support Auth0 Organizations.
- Adds a configurable 'Organization' option to the plugin's UI within the WordPress Admin Dashboard.
- Once defined, the Organization Id is passed along to the Universal Login Page.
- The org_id claim on JWTs is validated against the configured organization.
- Invitations (?invitation,organization,organization_name query parameters) are automatically detected and handled.
- Updated README with details about Organizations.
- Added additional tests covering these changes
=> [SDK-2376] Add Organizations support

CHANGELOG.md, WP_Auth0.php, readme.txt
**Fixed**
- Update client configuration url for embedded logins [\#832](https://github.com/auth0/wp-auth0/pull/832) ([evansims](https://github.com/evansims))
=> Release 4.3.1

lib/WP_Auth0_UsersRepo.php
The WP_Auth0_UsersRepo class manages WordPress user meta that is stored by Auth0.
The class contains a series of filters that allow developers to short-circuit methods. The idea behind this is that developers can implement their own way of managing user metadata stored by Auth0.
Currently the method for updating metadata does not pass the `$value` that is being updated. It only passes the key, which makes it impossible to adequately short-circuit.
- #811
- #812
The current test in [`TestUserRepoMeta::testUpdateMetaFilterWorksProperly`](https://github.com/tharsheblows/wp-auth0/blob/27bfc3a41a400caa536c91c0b4b53152c45fdf28/tests/testUserRepoMeta.php#L202-L233) does not adequately test this feature and should be updated.
This PR does not update the test.
- I added the proper doc block above …
=> fix(UsersRepo): pass `$value` in `auth0_update_meta` filter

CHANGELOG.md, LICENSE.md, wpAuth0.php
Introducing V5 of WP-Auth0 ("Login by Auth0"), a major redesign and upgrade to our WordPress integration plugin. V5 includes many new features and changes:
- [WordPress 6](https://wordpress.org/support/wordpress-version/version-6-0/) and [PHP 8](https://www.php.net/releases/8.0/en.php) support
- Integration with the [Auth0-PHP SDK](https://github.com/auth0/auth0-php), and access to its entire API (including Management API calls)
- High performance background sync using [WordPress' Cron](https://developer.wordpress.org/plugins/cron/) feature
- "Flexible identifier" support, allowing users to sign in using multiple connection types without requiring extra configuration
- Expanded control over how sign ins without matching existing WordPress accounts are handled
- Enhanced session pairing …
=> Release 5.0

lib/WP_Auth0_ErrorLog.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php, tests/Unit/ErrorLogTest.php
This PR allows the ability to disable the logging of Auth0 errors in Wordpress. This is useful to reduce load, especially in hosted multisite configurations which can have many instances of `auth0_error_log` forced to stay in memory and to load on every request.
> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. …
=> Add option to disable logs in Wordpress

CHANGELOG.md, wpAuth0.php
[Full Changelog](https://github.com/auth0/wp-auth0/compare/5.0.0...5.0.1)
**Fixed**
- Resolves an issue which sometimes prevented the plugin from being activated on WordPress 6
=> Release 5.0.1

lib/WP_Auth0_ErrorLog.php, lib/WP_Auth0_Nonce_Handler.php, lib/WP_Auth0_Options.php, lib/admin/WP_Auth0_Admin_Advanced.php
This PR adds a new cookie domain configuration option from within the Advanced settings UI.
This will allow you to override the default cookie domain of the current domain, and allow you to assign something like `.domain.example` so that the cookie is accessible from subdomains.
=> feat: Add cookie domain configuration to Advanced settings UI.
